"use client";

import type { FormEvent, ReactNode } from "react";
import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, Boxes, CalendarClock, CarFront, Check, ChevronDown, FileBarChart,
  LoaderCircle, Plus, ReceiptText, Save, Search, Sparkles, UploadCloud, UsersRound, WalletCards
} from "lucide-react";

type Row = Record<string, unknown>;
type Data = Record<string, Row[]>;
type Kind = "finance" | "hr" | "warehouse" | "fleet" | "reports";
type SubmitFactory = (entity: string, success: string) => (event: FormEvent<HTMLFormElement>) => void;

type Props = {
  workspaceId: string;
  kind: Kind;
  data: Data;
  canWrite: boolean;
  referenceDate: string;
};

type FormField = {
  name: string;
  label: string;
  type?: "text" | "email" | "date" | "datetime-local" | "number" | "select";
  required?: boolean;
  defaultValue?: string;
  placeholder?: string;
  options?: Array<[string, string]>;
  rows?: Row[];
  labelKey?: string;
};

function money(value: unknown) {
  return new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN", maximumFractionDigits: 2 }).format(Number(value ?? 0));
}

function number(value: unknown) {
  return new Intl.NumberFormat("pl-PL", { maximumFractionDigits: 2 }).format(Number(value ?? 0));
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function normalized(value: unknown) {
  return String(value ?? "").toLocaleLowerCase("pl").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

function matches(row: Row, query: string, extra = "") {
  return !query || normalized(`${JSON.stringify(row)} ${extra}`).includes(normalized(query));
}

function nameOf(row: Row, key = "name") {
  return String(row[key] ?? row.id ?? "—");
}

function SearchBar({ value, onChange, kind }: { value: string; onChange: (value: string) => void; kind: Kind }) {
  const placeholders: Record<Kind, string> = {
    finance: "Szukaj faktury, kontrahenta, inwestycji lub statusu",
    hr: "Szukaj pracownika, stanowiska, uprawnienia lub urlopu",
    warehouse: "Szukaj materiału, SKU, WZ/PZ, magazynu lub inwestycji",
    fleet: "Szukaj rejestracji, VIN, serwisu, tankowania lub terminu",
    reports: "Szukaj raportu, typu, okresu lub statusu"
  };
  return <label className="ops-search"><Search size={17} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholders[kind]} /><span>{value ? "Wyniki filtrowane" : "Wszystkie rekordy"}</span></label>;
}

function Empty({ children = "Brak pasujących rekordów." }: { children?: ReactNode }) {
  return <p className="ops-simple-list__empty">{children}</p>;
}

function SimpleList({ children }: { children: ReactNode }) {
  return <div className="ops-simple-list">{children}</div>;
}

function ListRow({ id, top, title, detail }: { id: string; top: ReactNode; title: ReactNode; detail: ReactNode }) {
  return <div key={id}><span>{top}</span><strong>{title}</strong><div className="ops-list-row__detail">{detail}</div></div>;
}

function Metric({ icon, title, value, caption, children }: { icon: ReactNode; title: string; value: ReactNode; caption: string; children: ReactNode }) {
  return <details className="ops-metric-card"><summary><span className="ops-metric-card__icon">{icon}</span><span>{title}</span><strong>{value}</strong><small>{caption}</small><ChevronDown size={16} /></summary><div className="ops-metric-card__details">{children}</div></details>;
}

function Panel({ title, eyebrow, meta, wide = false, open = false, children }: { title: string; eyebrow?: string; meta?: ReactNode; wide?: boolean; open?: boolean; children: ReactNode }) {
  return <details className={`ops-panel ops-disclosure ${wide ? "ops-panel--wide" : ""}`} open={open}><summary className="ops-panel__summary"><div>{eyebrow ? <p className="eyebrow">{eyebrow}</p> : null}<h2>{title}</h2></div>{meta ? <span>{meta}</span> : null}<ChevronDown size={18} /></summary><div className="ops-panel__content">{children}</div></details>;
}

function Field({ field }: { field: FormField }) {
  if (field.rows) {
    return <label>{field.label}<select name={field.name} required={field.required} defaultValue={field.defaultValue ?? ""}><option value="">{field.placeholder ?? "Wybierz"}</option>{field.rows.map((row) => <option key={String(row.id)} value={String(row.id)}>{nameOf(row, field.labelKey)}</option>)}</select></label>;
  }
  if (field.type === "select") {
    return <label>{field.label}<select name={field.name} required={field.required} defaultValue={field.defaultValue ?? field.options?.[0]?.[0] ?? ""}>{field.options?.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>;
  }
  return <label>{field.label}<input name={field.name} type={field.type === "number" ? "text" : field.type ?? "text"} inputMode={field.type === "number" ? "decimal" : undefined} required={field.required} defaultValue={field.defaultValue} placeholder={field.placeholder} /></label>;
}

function RecordForm({ title, entity, success, fields, submit, pending, wide = false, button = "Zapisz" }: { title: string; entity: string; success: string; fields: FormField[]; submit: SubmitFactory; pending: boolean; wide?: boolean; button?: string }) {
  return <Panel title={title} wide={wide}><form onSubmit={submit(entity, success)} className="ops-form"><div className="ops-auto-form-grid">{fields.map((field) => <Field key={field.name} field={field} />)}</div><button disabled={pending} className="primary-button">{pending ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />}{button}</button></form></Panel>;
}

function InlineAction({ entity, success, fields, label, submit, pending, danger = false }: { entity: string; success: string; fields: Record<string, string>; label: string; submit: SubmitFactory; pending: boolean; danger?: boolean }) {
  return <form className="ops-inline-action" onSubmit={submit(entity, success)}>{Object.entries(fields).map(([name, value]) => <input key={name} type="hidden" name={name} value={value} />)}<button className={danger ? "reject-button" : "approve-button"} disabled={pending}>{pending ? <LoaderCircle className="spin" size={14} /> : <Check size={14} />}{label}</button></form>;
}

function AiImports({ mode, workspaceId, imports, projects, warehouses, canWrite, pending, submit, query }: {
  mode: "finance" | "warehouse"; workspaceId: string; imports: Row[]; projects: Row[]; warehouses: Row[];
  canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string;
}) {
  const visible = imports.filter((row) => matches(row, query));
  const toImport = imports.filter((row) => !row.importedId).length;
  return <Panel title={mode === "finance" ? "Faktury odczytane przez AI" : "Faktury i WZ odczytane przez AI"} eyebrow="Automatyczna dekretacja" meta={`${toImport} do zaczytania`} wide open>
    <div className="ops-ai-intake-lead"><div><Sparkles size={19} /><p>AI odczytuje dokument, proponuje inwestycję albo rozrachunek ogólny i zachowuje źródło każdej pozycji.</p></div><Link href={`/workspace/companies/${workspaceId}/documents?upload=1`} className="secondary-button"><UploadCloud size={16} />Dodaj fakturę / WZ</Link></div>
    <div className="ops-import-list">
      {visible.map((item) => {
        const business = item.businessDocument && typeof item.businessDocument === "object" ? item.businessDocument as Row : {};
        const lines = Array.isArray(business.lines) ? business.lines as Row[] : [];
        const imported = Boolean(item.importedId);
        const project = projects.find((row) => row.id === item.projectId);
        return <details className="ops-import-row" key={String(item.documentId)}><summary><span className="ops-import-row__icon"><ReceiptText size={17} /></span><div><strong>{String(item.name)}</strong><small>{String(item.documentType)} · {String(business.documentNumber ?? "brak numeru")} · {lines.length} pozycji</small></div><span>{project ? String(project.name) : "Ogólny rozrachunek firmy"}</span><b className={`status-chip ${imported ? "status-chip--positive" : "status-chip--warning"}`}>{imported ? String(item.importedStatus ?? "zaczytano") : `${Math.round(Number(item.confidence ?? 0) * 100)}% AI`}</b><ChevronDown size={16} /></summary>
          <div className="ops-import-row__body"><dl><div><dt>Kontrahent</dt><dd>{String(business.supplierName ?? "—")}</dd></div><div><dt>NIP</dt><dd>{String(business.supplierTaxId ?? "—")}</dd></div><div><dt>Data</dt><dd>{String(business.issueDate ?? "—")}</dd></div><div><dt>Brutto</dt><dd>{money(business.grossAmount)}</dd></div></dl>
            <SimpleList>{lines.slice(0, 12).map((line, index) => <ListRow key={`${String(item.id)}-${index}`} id={`${String(item.id)}-${index}`} top={String(line.sku ?? index + 1)} title={String(line.description ?? "Pozycja")} detail={`${number(line.quantity)} ${String(line.unit ?? "")} · ${money(line.netAmount ?? line.grossAmount)}`} />)}{!lines.length ? <Empty>AI nie odczytało pozycji materiałowych.</Empty> : null}</SimpleList>
            {!imported && canWrite ? <form className="ops-import-action" onSubmit={submit(mode === "finance" ? "ai_invoice_import" : "ai_warehouse_import", mode === "finance" ? "Faktura została zaczytana i przypisana." : "Utworzono kontrolowany szkic PZ.")}><input type="hidden" name="documentId" value={String(item.documentId)} /><Field field={{ name: "projectId", label: "Przypisanie", rows: projects, placeholder: "Ogólny rozrachunek firmy", defaultValue: String(item.projectId ?? "") }} />{mode === "warehouse" ? <Field field={{ name: "warehouseId", label: "Magazyn", rows: warehouses, placeholder: "Magazyn główny / utwórz automatycznie", defaultValue: String(warehouses[0]?.id ?? "") }} /> : null}<button className="primary-button" disabled={pending}><Check size={16} />{mode === "finance" ? "Zaczytaj do Finansów" : "Utwórz szkic PZ"}</button></form> : null}
            {imported && mode === "warehouse" && item.importedStatus === "draft" && canWrite ? <form className="ops-import-action" onSubmit={submit("stock_movement_approve", "Ruch magazynowy został zatwierdzony.")}><input type="hidden" name="movementId" value={String(item.importedId)} /><input type="hidden" name="projectId" value={String(item.projectId ?? "")} /><p>Zatwierdzenie szkicu dopiero teraz zmieni stan magazynowy.</p><button className="primary-button" disabled={pending}><Check size={16} />Zatwierdź PZ</button></form> : null}
          </div>
        </details>;
      })}
      {!visible.length ? <Empty>Brak pasujących analiz AI. Dodaj dokument przez Wrzutnię.</Empty> : null}
    </div>
  </Panel>;
}

function Finance({ workspaceId, data, canWrite, pending, submit, query }: { workspaceId: string; data: Data; canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string }) {
  const counterparties = data.counterparties ?? [], invoices = data.invoices ?? [], invoiceLines = data.invoiceLines ?? [], payments = data.payments ?? [], commitments = data.commitments ?? [], allocations = data.allocations ?? [], projects = data.projects ?? [];
  const counterpartyNames = new Map(counterparties.map((row) => [String(row.id), String(row.name)]));
  const projectNames = new Map(projects.map((row) => [String(row.id), String(row.name)]));
  const allocationByInvoice = new Map(allocations.map((row) => [String(row.source_id), row]));
  const invoiceExtra = (row: Row) => `${counterpartyNames.get(String(row.counterparty_id)) ?? ""} ${projectNames.get(String(allocationByInvoice.get(String(row.id))?.project_id)) ?? "koszty ogolne"}`;
  const visible = invoices.filter((row) => matches(row, query, invoiceExtra(row)));
  const sales = invoices.filter((row) => row.direction === "sale"), purchases = invoices.filter((row) => row.direction === "purchase"), openRows = invoices.filter((row) => Number(row.gross_amount) > Number(row.paid_amount));
  const invoiceList = (rows: Row[]) => { const filtered = rows.filter((row) => matches(row, query, invoiceExtra(row))); return <SimpleList>{filtered.slice(0, 12).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.issue_date ?? row.due_date ?? "—")} title={String(row.invoice_number)} detail={`${counterpartyNames.get(String(row.counterparty_id)) ?? "Bez kontrahenta"} · ${money(row.gross_amount)}`} />)}{!filtered.length ? <Empty /> : null}</SimpleList>; };
  const salesValue = sales.reduce((sum, row) => sum + Number(row.gross_amount ?? 0), 0), purchasesValue = purchases.reduce((sum, row) => sum + Number(row.gross_amount ?? 0), 0), paidValue = invoices.reduce((sum, row) => sum + Number(row.paid_amount ?? 0), 0), openValue = openRows.reduce((sum, row) => sum + Number(row.gross_amount ?? 0) - Number(row.paid_amount ?? 0), 0);
  const forms = [
    { title: "Dodaj kontrahenta", entity: "counterparty", success: "Kontrahent został dodany.", fields: [{ name: "name", label: "Nazwa", required: true }, { name: "taxId", label: "NIP" }, { name: "role", label: "Rola", type: "select" as const, options: [["supplier", "Dostawca"], ["customer", "Klient"], ["subcontractor", "Podwykonawca"]] as Array<[string, string]> }] },
    { title: "Zarejestruj fakturę ręcznie", entity: "invoice", success: "Faktura została zapisana i przypisana.", wide: true, fields: [{ name: "invoiceNumber", label: "Numer", required: true }, { name: "direction", label: "Rodzaj", type: "select" as const, options: [["purchase", "Zakupowa"], ["sale", "Sprzedażowa"]] as Array<[string, string]> }, { name: "counterpartyId", label: "Kontrahent", rows: counterparties, placeholder: "Bez przypisania" }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Koszt ogólnofirmowy" }, { name: "issueDate", label: "Data wystawienia", type: "date" as const, defaultValue: today() }, { name: "dueDate", label: "Termin płatności", type: "date" as const }, { name: "netAmount", label: "Netto", type: "number" as const }, { name: "taxAmount", label: "VAT", type: "number" as const }, { name: "grossAmount", label: "Brutto", type: "number" as const, required: true }, { name: "lineDescription", label: "Opis głównej pozycji" }, { name: "lineQuantity", label: "Ilość", type: "number" as const }, { name: "lineUnit", label: "Jednostka" }, { name: "lineUnitPrice", label: "Cena jednostkowa", type: "number" as const }] },
    { title: "Zarejestruj płatność", entity: "payment", success: "Płatność została zapisana.", fields: [{ name: "invoiceId", label: "Faktura", rows: invoices.map((row) => ({ ...row, name: `${row.invoice_number} · ${money(row.gross_amount)}` })), required: true }, { name: "paymentDate", label: "Data", type: "date" as const, defaultValue: today() }, { name: "amount", label: "Kwota", type: "number" as const, required: true }, { name: "bankReference", label: "Referencja" }] },
    { title: "Dodaj zobowiązanie", entity: "commitment", success: "Zobowiązanie dodano do cash flow.", fields: [{ name: "description", label: "Opis", required: true }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Koszt ogólnofirmowy" }, { name: "amount", label: "Wartość", type: "number" as const, required: true }, { name: "expectedDate", label: "Planowana data", type: "date" as const }] }
  ];
  return <><section className="ops-metrics"><Metric icon={<WalletCards />} title="Sprzedaż brutto" value={money(salesValue)} caption="Kliknij: faktury sprzedażowe">{invoiceList(sales)}</Metric><Metric icon={<ReceiptText />} title="Zakupy brutto" value={money(purchasesValue)} caption="Kliknij: faktury zakupowe">{invoiceList(purchases)}</Metric><Metric icon={<Save />} title="Rozliczono" value={money(paidValue)} caption="Kliknij: płatności"><SimpleList>{payments.filter((row) => matches(row, query)).slice(0, 12).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.payment_date)} title={money(row.amount)} detail={String(row.bank_reference ?? "Płatność")} />)}</SimpleList></Metric><Metric icon={<CalendarClock />} title="Do rozliczenia" value={money(openValue)} caption="Kliknij: otwarte rozrachunki">{invoiceList(openRows)}</Metric></section>
    <AiImports mode="finance" workspaceId={workspaceId} imports={data.aiImports ?? []} projects={projects} warehouses={[]} canWrite={canWrite} pending={pending} submit={submit} query={query} />
    {canWrite ? <section className="ops-form-grid">{forms.map((form) => <RecordForm key={form.entity} {...form} submit={submit} pending={pending} />)}</section> : null}
    <Panel title="Faktury i rozrachunki" eyebrow="Rejestr finansowy" meta={`${visible.length} faktur`} wide open><div className="ops-table"><div className="ops-table__head"><span>Dokument</span><span>Kontrahent</span><span>Przypisanie</span><span>Brutto</span><span>Pozostało</span><span>Status</span></div>{visible.map((row) => { const allocation = allocationByInvoice.get(String(row.id)); return <div key={String(row.id)}><strong>{String(row.invoice_number)}</strong><span>{counterpartyNames.get(String(row.counterparty_id)) ?? "—"}</span><span>{allocation ? projectNames.get(String(allocation.project_id)) ?? "Inwestycja" : "Koszty ogólne"}</span><span>{money(row.gross_amount)}</span><span>{money(Number(row.gross_amount ?? 0) - Number(row.paid_amount ?? 0))}</span><span className="status-chip">{String(row.status)}</span></div>; })}{!visible.length ? <Empty /> : null}</div></Panel>
    <Panel title="Pozycje faktur" meta={`${invoiceLines.length} pozycji`} wide><SimpleList>{invoiceLines.filter((line) => matches(line, query, String(invoices.find((invoice) => invoice.id === line.invoice_id)?.invoice_number ?? ""))).map((line) => <ListRow key={String(line.id)} id={String(line.id)} top={String(invoices.find((invoice) => invoice.id === line.invoice_id)?.invoice_number ?? "Faktura")} title={String(line.description)} detail={`${number(line.quantity)} ${String(line.unit ?? "")} · ${money(line.gross_amount)}`} />)}{!invoiceLines.length ? <Empty /> : null}</SimpleList></Panel>
    <Panel title="Kontrahenci i zobowiązania" wide><div className="ops-split-lists"><SimpleList>{counterparties.filter((row) => matches(row, query)).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.role ?? "kontrahent")} title={String(row.name)} detail={`NIP ${String(row.tax_id ?? "—")}`} />)}</SimpleList><SimpleList>{commitments.filter((row) => matches(row, query, projectNames.get(String(row.project_id)) ?? "koszt ogolny")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.expected_date ?? "—")} title={String(row.description)} detail={`${money(row.amount)} · ${projectNames.get(String(row.project_id)) ?? "Koszt ogólny"}`} />)}</SimpleList></div></Panel>
  </>;
}

function Hr({ data, canWrite, pending, submit, query, referenceDate }: { data: Data; canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string; referenceDate: string }) {
  const employees = data.employees ?? [], employments = data.employments ?? [], qualifications = data.qualifications ?? [], exams = data.exams ?? [], leaves = data.leaves ?? [], timesheets = data.timesheets ?? [], projects = data.projects ?? [];
  const employeeNames = new Map(employees.map((row) => [String(row.id), `${row.first_name} ${row.last_name}`])), projectNames = new Map(projects.map((row) => [String(row.id), String(row.name)]));
  const employeeOptions = employees.map((row) => ({ ...row, name: employeeNames.get(String(row.id)) }));
  const visibleEmployees = employees.filter((row) => matches(row, query, String(employments.find((item) => item.employee_id === row.id)?.position ?? "")));
  const visibleTime = timesheets.filter((row) => matches(row, query, `${employeeNames.get(String(row.employee_id)) ?? ""} ${projectNames.get(String(row.project_id)) ?? ""}`));
  const referenceTime = Date.parse(referenceDate);
  const deadlineRows = [...qualifications, ...exams].filter((row) => row.valid_until);
  const expired = deadlineRows.filter((row) => Date.parse(String(row.valid_until)) < referenceTime);
  const expiring = deadlineRows.filter((row) => {
    const deadline = Date.parse(String(row.valid_until));
    return deadline >= referenceTime && deadline <= referenceTime + 30 * 86_400_000;
  });
  const forms = [
    { title: "Dodaj pracownika", entity: "employee", success: "Pracownik i zatrudnienie zostały zapisane.", wide: true, fields: [{ name: "firstName", label: "Imię", required: true }, { name: "lastName", label: "Nazwisko", required: true }, { name: "employeeNumber", label: "Numer pracownika" }, { name: "email", label: "E-mail", type: "email" as const }, { name: "phone", label: "Telefon" }, { name: "employmentType", label: "Forma zatrudnienia", type: "select" as const, options: [["employment_contract", "Umowa o pracę"], ["contract", "Umowa cywilna"], ["b2b", "B2B"]] as Array<[string, string]> }, { name: "position", label: "Stanowisko" }, { name: "hiredAt", label: "Data zatrudnienia", type: "date" as const, defaultValue: today() }, { name: "monthlyCost", label: "Koszt miesięczny", type: "number" as const }, { name: "hourlyCost", label: "Koszt godzinowy", type: "number" as const }] },
    { title: "Dodaj uprawnienie", entity: "qualification", success: "Uprawnienie zostało zapisane.", fields: [{ name: "employeeId", label: "Pracownik", rows: employeeOptions, required: true }, { name: "qualificationType", label: "Rodzaj", required: true, placeholder: "SEP, UDT, F-gazy" }, { name: "number", label: "Numer" }, { name: "validUntil", label: "Ważne do", type: "date" as const }] },
    { title: "Dodaj badanie medyczne", entity: "medical_exam", success: "Badanie medyczne zostało zapisane.", fields: [{ name: "employeeId", label: "Pracownik", rows: employeeOptions, required: true }, { name: "examType", label: "Rodzaj", required: true, placeholder: "Wstępne, okresowe, kontrolne" }, { name: "examinedAt", label: "Data badania", type: "date" as const, defaultValue: today() }, { name: "validUntil", label: "Ważne do", type: "date" as const, required: true }, { name: "result", label: "Wynik", type: "select" as const, options: [["fit", "Zdolny"], ["fit_with_restrictions", "Zdolny z ograniczeniami"], ["unfit", "Niezdolny"]] as Array<[string, string]> }] },
    { title: "Czas pracy", entity: "timesheet", success: "Czas pracy został zapisany.", fields: [{ name: "employeeId", label: "Pracownik", rows: employeeOptions, required: true }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Koszt ogólny" }, { name: "workDate", label: "Data", type: "date" as const, defaultValue: today() }, { name: "hours", label: "Godziny", type: "number" as const, required: true }, { name: "overtimeHours", label: "Nadgodziny", type: "number" as const }] },
    { title: "Wniosek urlopowy", entity: "leave_request", success: "Wniosek urlopowy został zapisany.", fields: [{ name: "employeeId", label: "Pracownik", rows: employeeOptions, required: true }, { name: "dateFrom", label: "Od", type: "date" as const, required: true }, { name: "dateTo", label: "Do", type: "date" as const, required: true }, { name: "leaveType", label: "Rodzaj", type: "select" as const, options: [["annual", "Wypoczynkowy"], ["on_demand", "Na żądanie"], ["unpaid", "Bezpłatny"], ["sick", "Chorobowe"]] as Array<[string, string]> }, { name: "days", label: "Liczba dni", type: "number" as const, required: true }] }
  ];
  const hours = timesheets.reduce((sum, row) => sum + Number(row.hours ?? 0) + Number(row.overtime_hours ?? 0), 0);
  return <><section className="ops-metrics"><Metric icon={<UsersRound />} title="Pracownicy aktywni" value={employees.filter((row) => row.status === "active").length} caption="Kliknij: lista osób"><SimpleList>{visibleEmployees.filter((row) => row.status === "active").map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.employee_number ?? "—")} title={employeeNames.get(String(row.id))} detail={String(employments.find((item) => item.employee_id === row.id)?.position ?? "Bez stanowiska")} />)}</SimpleList></Metric><Metric icon={<CalendarClock />} title="Godziny" value={`${number(hours)} h`} caption="Kliknij: wpisy czasu"><SimpleList>{visibleTime.slice(0, 12).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.work_date)} title={employeeNames.get(String(row.employee_id)) ?? "Pracownik"} detail={`${number(row.hours)} h · ${projectNames.get(String(row.project_id)) ?? "Koszt ogólny"}`} />)}</SimpleList></Metric><Metric icon={<AlertTriangle />} title="Terminy do 30 dni" value={expiring.length} caption="Kliknij: przyszłe terminy"><SimpleList>{expiring.filter((row) => matches(row, query, employeeNames.get(String(row.employee_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.valid_until)} title={employeeNames.get(String(row.employee_id)) ?? "Pracownik"} detail={String(row.qualification_type ?? row.exam_type ?? "Termin")} />)}</SimpleList></Metric><Metric icon={<FileBarChart />} title="Urlopy oczekujące" value={leaves.filter((row) => row.status === "pending").length} caption="Kliknij: decyzje"><SimpleList>{leaves.filter((row) => row.status === "pending" && matches(row, query, employeeNames.get(String(row.employee_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={`${String(row.date_from)}–${String(row.date_to)}`} title={employeeNames.get(String(row.employee_id)) ?? "Pracownik"} detail={<span>{number(row.days)} dni · {String(row.leave_type)}{canWrite ? <span className="ops-inline-actions"><InlineAction entity="leave_decision" success="Urlop został zatwierdzony." fields={{ leaveId: String(row.id), decision: "approved" }} label="Zatwierdź" submit={submit} pending={pending} /><InlineAction entity="leave_decision" success="Urlop został odrzucony." fields={{ leaveId: String(row.id), decision: "rejected" }} label="Odrzuć" submit={submit} pending={pending} danger /></span> : null}</span>} />)}</SimpleList></Metric></section>
    {canWrite ? <section className="ops-form-grid">{forms.map((form) => <RecordForm key={form.entity} {...form} submit={submit} pending={pending} />)}</section> : null}
    <Panel title="Czas pracy do zatwierdzenia" meta={`${timesheets.filter((row) => row.status === "submitted").length} wpisów`} wide><SimpleList>{timesheets.filter((row) => row.status === "submitted" && matches(row, query, employeeNames.get(String(row.employee_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.work_date)} title={employeeNames.get(String(row.employee_id)) ?? "Pracownik"} detail={<span>{number(row.hours)} h · {projectNames.get(String(row.project_id)) ?? "Koszt ogólny"}{canWrite ? <span className="ops-inline-actions"><InlineAction entity="timesheet_decision" success="Czas pracy zatwierdzono." fields={{ timesheetId: String(row.id), decision: "approved" }} label="Zatwierdź" submit={submit} pending={pending} /><InlineAction entity="timesheet_decision" success="Czas pracy odrzucono." fields={{ timesheetId: String(row.id), decision: "rejected" }} label="Odrzuć" submit={submit} pending={pending} danger /></span> : null}</span>} />)}{!timesheets.some((row) => row.status === "submitted") ? <Empty>Brak wpisów oczekujących na decyzję.</Empty> : null}</SimpleList></Panel>
    <Panel title="Wygasłe badania i uprawnienia" meta={`${expired.length} terminów`} wide><SimpleList>{expired.filter((row) => matches(row, query, employeeNames.get(String(row.employee_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.valid_until)} title={employeeNames.get(String(row.employee_id)) ?? "Pracownik"} detail={String(row.qualification_type ?? row.exam_type ?? "Termin")} />)}{!expired.length ? <Empty>Brak wygasłych terminów.</Empty> : null}</SimpleList></Panel>
    <Panel title="Pracownicy" eyebrow="Rejestr kadrowy" meta={`${visibleEmployees.length} osób`} wide open><div className="employee-register">{visibleEmployees.map((employee) => { const employment = employments.find((row) => row.employee_id === employee.id); const qualificationsForEmployee = qualifications.filter((row) => row.employee_id === employee.id); const examsForEmployee = exams.filter((row) => row.employee_id === employee.id); const hoursForEmployee = visibleTime.filter((row) => row.employee_id === employee.id).reduce((sum, row) => sum + Number(row.hours ?? 0), 0); return <details key={String(employee.id)}><summary><span className="employee-avatar">{String(employee.first_name).slice(0, 1)}{String(employee.last_name).slice(0, 1)}</span><div><strong>{employeeNames.get(String(employee.id))}</strong><small>{String(employment?.position ?? "Bez stanowiska")} · {String(employee.status)}</small></div><b>{number(hoursForEmployee)} h</b></summary><div className="employee-details"><dl><div><dt>Forma</dt><dd>{String(employment?.employment_type ?? "—")}</dd></div><div><dt>Od</dt><dd>{String(employment?.valid_from ?? employee.hired_at ?? "—")}</dd></div><div><dt>Koszt miesięczny</dt><dd>{employment?.monthly_cost ? money(employment.monthly_cost) : "—"}</dd></div><div><dt>Koszt godzinowy</dt><dd>{employment?.hourly_cost ? money(employment.hourly_cost) : "—"}</dd></div></dl><p><strong>Uprawnienia:</strong> {qualificationsForEmployee.length ? qualificationsForEmployee.map((row) => `${row.qualification_type} (${row.valid_until ?? "bezterminowo"})`).join(" · ") : "brak"}</p><p><strong>Badania:</strong> {examsForEmployee.length ? examsForEmployee.map((row) => `${row.exam_type} (${row.valid_until ?? "bez terminu"})`).join(" · ") : "brak"}</p><p><strong>Kontakt:</strong> {String(employee.email ?? "—")} · {String(employee.phone ?? "—")}</p>{canWrite ? <InlineAction entity="employee_status" success="Status pracownika został zmieniony." fields={{ employeeId: String(employee.id), status: employee.status === "active" ? "inactive" : "active" }} label={employee.status === "active" ? "Dezaktywuj" : "Aktywuj"} submit={submit} pending={pending} danger={employee.status === "active"} /> : null}</div></details>; })}{!visibleEmployees.length ? <Empty /> : null}</div></Panel>
  </>;
}

function Warehouse({ workspaceId, data, canWrite, pending, submit, query }: { workspaceId: string; data: Data; canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string }) {
  const warehouses = data.warehouses ?? [], items = data.items ?? [], movements = data.movements ?? [], lines = data.lines ?? [], balances = data.balances ?? [], reservations = data.reservations ?? [], projects = data.projects ?? [];
  const warehouseNames = new Map(warehouses.map((row) => [String(row.id), String(row.name)])), itemById = new Map(items.map((row) => [String(row.id), row])), projectNames = new Map(projects.map((row) => [String(row.id), String(row.name)]));
  const visibleWarehouses = warehouses.filter((row) => matches(row, query)), visibleItems = items.filter((row) => matches(row, query));
  const visibleMovements = movements.filter((row) => matches(row, query, `${warehouseNames.get(String(row.warehouse_id)) ?? ""} ${projectNames.get(String(row.project_id)) ?? "ogolny"}`));
  const visibleBalances = balances.filter((row) => matches(row, query, `${warehouseNames.get(String(row.warehouseId)) ?? ""} ${JSON.stringify(itemById.get(String(row.stockItemId)) ?? {})}`));
  const latestCost = new Map<string, number>();
  movements.forEach((movement) => lines.filter((line) => line.movement_id === movement.id).forEach((line) => {
    if (Number(line.unit_cost ?? 0) > 0 && !latestCost.has(String(line.stock_item_id))) latestCost.set(String(line.stock_item_id), Number(line.unit_cost));
  }));
  const stockValue = balances.reduce((sum, balance) => sum + Number(balance.quantity ?? 0) * Number(latestCost.get(String(balance.stockItemId)) ?? 0), 0);
  const forms = [
    { title: "Dodaj magazyn", entity: "warehouse", success: "Magazyn został utworzony.", fields: [{ name: "name", label: "Nazwa", required: true }, { name: "location", label: "Lokalizacja" }, { name: "warehouseType", label: "Typ", type: "select" as const, options: [["central", "Centralny"], ["project", "Budowa"], ["vehicle", "Mobilny / pojazd"]] as Array<[string, string]> }] },
    { title: "Dodaj kartotekę", entity: "stock_item", success: "Kartoteka została dodana.", fields: [{ name: "name", label: "Nazwa", required: true }, { name: "sku", label: "SKU" }, { name: "itemType", label: "Typ", type: "select" as const, options: [["material", "Materiał"], ["device", "Urządzenie"], ["tool", "Narzędzie"]] as Array<[string, string]> }, { name: "unit", label: "Jednostka", required: true }, { name: "minimumStock", label: "Stan minimalny", type: "number" as const }] },
    { title: "Zarejestruj ruch ręcznie", entity: "stock_movement", success: "Ruch został zatwierdzony.", wide: true, fields: [{ name: "movementType", label: "Typ", type: "select" as const, options: [["PZ", "PZ"], ["WZ", "WZ"], ["RW", "RW"], ["ZW", "ZW"], ["MM", "MM"]] as Array<[string, string]> }, { name: "warehouseId", label: "Magazyn", rows: warehouses, required: true }, { name: "targetWarehouseId", label: "Magazyn docelowy", rows: warehouses, placeholder: "Tylko dla MM" }, { name: "stockItemId", label: "Kartoteka", rows: items, required: true }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Ruch ogólnofirmowy" }, { name: "quantity", label: "Ilość", type: "number" as const, required: true }, { name: "unitCost", label: "Koszt jednostkowy", type: "number" as const }, { name: "documentNumber", label: "Numer dokumentu" }, { name: "movementDate", label: "Data ruchu", type: "date" as const, defaultValue: today() }] },
    { title: "Zarezerwuj materiał", entity: "reservation", success: "Materiał został zarezerwowany dla inwestycji.", fields: [{ name: "projectId", label: "Inwestycja", rows: projects, required: true }, { name: "warehouseId", label: "Magazyn", rows: warehouses, required: true }, { name: "stockItemId", label: "Kartoteka", rows: items, required: true }, { name: "quantity", label: "Ilość", type: "number" as const, required: true }, { name: "requiredAt", label: "Potrzebne na", type: "date" as const, required: true }] }
  ];
  return <><section className="ops-metrics"><Metric icon={<Boxes />} title="Magazyny" value={warehouses.length} caption="Kliknij: lista lokalizacji"><SimpleList>{visibleWarehouses.map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.warehouse_type)} title={String(row.name)} detail={String(row.location ?? "Brak lokalizacji")} />)}</SimpleList></Metric><Metric icon={<Boxes />} title="Kartoteki" value={items.length} caption="Kliknij: materiały i narzędzia"><SimpleList>{visibleItems.slice(0, 20).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.sku ?? "—")} title={String(row.name)} detail={`${String(row.item_type)} · ${String(row.unit)}`} />)}</SimpleList></Metric><Metric icon={<ReceiptText />} title="Ruchy zatwierdzone" value={movements.filter((row) => row.status === "approved").length} caption="Kliknij: PZ/WZ/RW/ZW/MM"><SimpleList>{visibleMovements.filter((row) => row.status === "approved").slice(0, 15).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.movement_date)} title={`${String(row.movement_type)} · ${String(row.document_number ?? "bez numeru")}`} detail={`${warehouseNames.get(String(row.warehouse_id)) ?? "Magazyn"} · ${projectNames.get(String(row.project_id)) ?? "Ruch ogólny"}`} />)}</SimpleList></Metric><Metric icon={<WalletCards />} title="Wartość zapasu" value={money(stockValue)} caption="Stan × ostatni koszt"><SimpleList>{visibleBalances.slice(0, 15).map((balance) => <ListRow key={`${String(balance.warehouseId)}-${String(balance.stockItemId)}`} id={`${String(balance.warehouseId)}-${String(balance.stockItemId)}`} top={warehouseNames.get(String(balance.warehouseId)) ?? "Magazyn"} title={String(itemById.get(String(balance.stockItemId))?.name ?? "Kartoteka")} detail={money(Number(balance.quantity ?? 0) * Number(latestCost.get(String(balance.stockItemId)) ?? 0))} />)}</SimpleList></Metric></section>
    <AiImports mode="warehouse" workspaceId={workspaceId} imports={data.aiImports ?? []} projects={projects} warehouses={warehouses} canWrite={canWrite} pending={pending} submit={submit} query={query} />
    {canWrite ? <section className="ops-form-grid">{forms.map((form) => <RecordForm key={form.entity} {...form} submit={submit} pending={pending} />)}</section> : null}
    <Panel title="Stany według magazynu i kartoteki" eyebrow="Zatwierdzone ruchy" meta={`${visibleBalances.length} pozycji`} wide open><div className="ops-table ops-table--stock"><div className="ops-table__head"><span>Magazyn</span><span>Kartoteka</span><span>SKU</span><span>Ilość</span><span>Jednostka</span></div>{visibleBalances.map((balance) => { const item = itemById.get(String(balance.stockItemId)); return <div key={`${String(balance.warehouseId)}-${String(balance.stockItemId)}`}><strong>{warehouseNames.get(String(balance.warehouseId)) ?? "—"}</strong><span>{String(item?.name ?? "—")}</span><span>{String(item?.sku ?? "—")}</span><span>{number(balance.quantity)}</span><span>{String(item?.unit ?? "—")}</span></div>; })}{!visibleBalances.length ? <Empty /> : null}</div></Panel>
    <Panel title="Ruchy magazynowe" meta={`${visibleMovements.length} dokumentów`} wide><SimpleList>{visibleMovements.map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.movement_date)} title={`${String(row.movement_type)} · ${String(row.document_number ?? "bez numeru")}`} detail={`${warehouseNames.get(String(row.warehouse_id)) ?? "Magazyn"} · ${projectNames.get(String(row.project_id)) ?? "Ogólnofirmowy"} · ${String(row.status)}`} />)}</SimpleList></Panel>
    <Panel title="Rezerwacje materiałowe" meta={`${reservations.length} rezerwacji`} wide><SimpleList>{reservations.filter((row) => matches(row, query, `${projectNames.get(String(row.project_id)) ?? ""} ${String(itemById.get(String(row.stock_item_id))?.name ?? "")}`)).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.required_at ?? "bez terminu")} title={String(itemById.get(String(row.stock_item_id))?.name ?? "Kartoteka")} detail={`${number(row.quantity)} ${String(itemById.get(String(row.stock_item_id))?.unit ?? "")} · ${projectNames.get(String(row.project_id)) ?? "Inwestycja"} · ${String(row.status)}`} />)}{!reservations.length ? <Empty>Brak rezerwacji materiałowych.</Empty> : null}</SimpleList></Panel>
  </>;
}

function Fleet({ data, canWrite, pending, submit, query, referenceDate }: { data: Data; canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string; referenceDate: string }) {
  const vehicles = data.vehicles ?? [], fuel = data.fuel ?? [], trips = data.trips ?? [], service = data.service ?? [], documents = data.documents ?? [], damages = data.damages ?? [], projects = data.projects ?? [], employees = data.employees ?? [];
  const vehicleNames = new Map(vehicles.map((row) => [String(row.id), `${row.registration_number} ${row.make ?? ""} ${row.model ?? ""}`])), projectNames = new Map(projects.map((row) => [String(row.id), String(row.name)])), employeeNames = new Map(employees.map((row) => [String(row.id), `${row.first_name} ${row.last_name}`]));
  const employeeOptions = employees.map((row) => ({ ...row, name: employeeNames.get(String(row.id)) }));
  const visibleVehicles = vehicles.filter((row) => matches(row, query)), visibleFuel = fuel.filter((row) => matches(row, query, `${vehicleNames.get(String(row.vehicle_id)) ?? ""} ${projectNames.get(String(row.project_id)) ?? "ogolny"}`)), visibleService = service.filter((row) => matches(row, query, vehicleNames.get(String(row.vehicle_id)) ?? "")), visibleDocuments = documents.filter((row) => matches(row, query, vehicleNames.get(String(row.vehicle_id)) ?? ""));
  const referenceTime = Date.parse(referenceDate);
  const expired = documents.filter((row) => row.valid_until && Date.parse(String(row.valid_until)) < referenceTime);
  const due = documents.filter((row) => { const deadline = Date.parse(String(row.valid_until ?? "")); return Number.isFinite(deadline) && deadline >= referenceTime && deadline <= referenceTime + 30 * 86_400_000; });
  const fuelCost = fuel.reduce((sum, row) => sum + Number(row.gross_amount ?? 0), 0), serviceCost = service.reduce((sum, row) => sum + Number(row.cost ?? 0), 0), damageCost = damages.reduce((sum, row) => sum + Number(row.cost ?? 0), 0);
  const totalDistance = trips.reduce((sum, row) => sum + Number(row.distance_km ?? 0), 0), fleetCostPerKm = totalDistance > 0 ? (fuelCost + serviceCost + damageCost) / totalDistance : 0;
  const forms = [
    { title: "Dodaj pojazd lub maszynę", entity: "vehicle", success: "Pojazd został dodany.", wide: true, fields: [{ name: "registrationNumber", label: "Rejestracja", required: true }, { name: "vehicleType", label: "Typ", type: "select" as const, options: [["car", "Samochód"], ["truck", "Ciężarówka"], ["machine", "Maszyna"], ["trailer", "Przyczepa"]] as Array<[string, string]> }, { name: "ownershipType", label: "Forma własności", type: "select" as const, options: [["owned", "Własność"], ["lease", "Leasing"], ["rental", "Najem"]] as Array<[string, string]> }, { name: "make", label: "Marka" }, { name: "model", label: "Model" }, { name: "productionYear", label: "Rok", type: "number" as const }, { name: "vin", label: "VIN" }, { name: "currentMileage", label: "Przebieg", type: "number" as const }] },
    { title: "Tankowanie", entity: "fuel_entry", success: "Tankowanie zostało zapisane.", fields: [{ name: "vehicleId", label: "Pojazd", rows: vehicles, labelKey: "registration_number", required: true }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Koszt ogólny" }, { name: "liters", label: "Litry", type: "number" as const, required: true }, { name: "grossAmount", label: "Koszt brutto", type: "number" as const, required: true }, { name: "mileage", label: "Przebieg", type: "number" as const }, { name: "fueledAt", label: "Data i czas", type: "datetime-local" as const }] },
    { title: "Przejazd", entity: "trip", success: "Przejazd został zapisany i przypisany.", wide: true, fields: [{ name: "vehicleId", label: "Pojazd", rows: vehicles, labelKey: "registration_number", required: true }, { name: "employeeId", label: "Kierowca", rows: employeeOptions, placeholder: "Bez kierowcy" }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Przejazd ogólny" }, { name: "startedAt", label: "Start", type: "datetime-local" as const }, { name: "finishedAt", label: "Koniec", type: "datetime-local" as const }, { name: "startLocation", label: "Skąd" }, { name: "endLocation", label: "Dokąd" }, { name: "distanceKm", label: "Dystans km", type: "number" as const, required: true }, { name: "purpose", label: "Cel przejazdu", required: true }] },
    { title: "Serwis", entity: "service_order", success: "Serwis został zapisany.", fields: [{ name: "vehicleId", label: "Pojazd", rows: vehicles, labelKey: "registration_number", required: true }, { name: "serviceType", label: "Rodzaj serwisu", required: true }, { name: "openedAt", label: "Otwarcie", type: "date" as const, defaultValue: today() }, { name: "cost", label: "Koszt", type: "number" as const }, { name: "nextDueDate", label: "Następna data", type: "date" as const }, { name: "nextDueMileage", label: "Następny przebieg", type: "number" as const }] },
    { title: "Dokument i termin", entity: "vehicle_document", success: "Dokument został zapisany.", fields: [{ name: "vehicleId", label: "Pojazd", rows: vehicles, labelKey: "registration_number", required: true }, { name: "documentType", label: "Rodzaj", type: "select" as const, options: [["inspection", "Badanie techniczne"], ["insurance", "OC / AC"], ["lease", "Leasing"], ["permit", "Pozwolenie / UDT"]] as Array<[string, string]> }, { name: "number", label: "Numer" }, { name: "validFrom", label: "Od", type: "date" as const }, { name: "validUntil", label: "Ważne do", type: "date" as const }] },
    { title: "Zgłoś szkodę", entity: "damage_case", success: "Szkoda została zarejestrowana.", fields: [{ name: "vehicleId", label: "Pojazd", rows: vehicles, labelKey: "registration_number", required: true }, { name: "employeeId", label: "Kierowca", rows: employeeOptions, placeholder: "Nie przypisano" }, { name: "occurredAt", label: "Data zdarzenia", type: "datetime-local" as const }, { name: "description", label: "Opis szkody", required: true }, { name: "cost", label: "Szacowany koszt", type: "number" as const }] }
  ];
  return <><section className="ops-metrics"><Metric icon={<CarFront />} title="Pojazdy aktywne" value={vehicles.filter((row) => row.status === "active").length} caption="Kliknij: lista floty"><SimpleList>{visibleVehicles.filter((row) => row.status === "active").map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.vehicle_type)} title={String(row.registration_number)} detail={`${String(row.make ?? "")} ${String(row.model ?? "")} · ${number(row.current_mileage)} km`} />)}</SimpleList></Metric><Metric icon={<WalletCards />} title="Koszt / km" value={totalDistance ? `${money(fleetCostPerKm)}/km` : "—"} caption={`${number(totalDistance)} km przejazdów`}><SimpleList>{trips.filter((row) => matches(row, query, `${vehicleNames.get(String(row.vehicle_id)) ?? ""} ${projectNames.get(String(row.project_id)) ?? ""}`)).slice(0, 15).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.started_at ?? "").slice(0, 10)} title={vehicleNames.get(String(row.vehicle_id)) ?? "Pojazd"} detail={`${number(row.distance_km)} km · ${projectNames.get(String(row.project_id)) ?? "Ogólny"}`} />)}</SimpleList></Metric><Metric icon={<Save />} title="Serwis" value={money(serviceCost)} caption="Kliknij: zlecenia"><SimpleList>{visibleService.slice(0, 15).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.opened_at)} title={vehicleNames.get(String(row.vehicle_id)) ?? "Pojazd"} detail={`${String(row.service_type)} · ${money(row.cost)} · ${String(row.status)}`} />)}</SimpleList></Metric><Metric icon={<CalendarClock />} title="Terminy do 30 dni" value={due.length} caption="Bez wygasłych dokumentów"><SimpleList>{due.filter((row) => matches(row, query, vehicleNames.get(String(row.vehicle_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.valid_until)} title={vehicleNames.get(String(row.vehicle_id)) ?? "Pojazd"} detail={`${String(row.document_type)} · ${String(row.number ?? "—")}`} />)}</SimpleList></Metric></section>
    {canWrite ? <section className="ops-form-grid">{forms.map((form) => <RecordForm key={form.entity} {...form} submit={submit} pending={pending} />)}</section> : null}
    <Panel title="Wygasłe dokumenty floty" meta={`${expired.length} terminów`} wide><SimpleList>{expired.filter((row) => matches(row, query, vehicleNames.get(String(row.vehicle_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.valid_until)} title={vehicleNames.get(String(row.vehicle_id)) ?? "Pojazd"} detail={`${String(row.document_type)} · ${String(row.number ?? "—")}`} />)}{!expired.length ? <Empty>Brak wygasłych dokumentów.</Empty> : null}</SimpleList></Panel>
    <Panel title="Szkody" meta={`${damages.length} zgłoszeń`} wide><SimpleList>{damages.filter((row) => matches(row, query, vehicleNames.get(String(row.vehicle_id)) ?? "")).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.occurred_at ?? "").slice(0, 10)} title={vehicleNames.get(String(row.vehicle_id)) ?? "Pojazd"} detail={`${String(row.description)} · ${money(row.cost)} · ${String(row.status)}`} />)}{!damages.length ? <Empty>Brak zgłoszonych szkód.</Empty> : null}</SimpleList></Panel>
    <Panel title="Pojazdy i maszyny" eyebrow="Rejestr floty" meta={`${visibleVehicles.length} rekordów`} wide open><div className="fleet-register">{visibleVehicles.map((vehicle) => { const vehicleFuel = visibleFuel.filter((row) => row.vehicle_id === vehicle.id), vehicleService = visibleService.filter((row) => row.vehicle_id === vehicle.id), vehicleDocs = visibleDocuments.filter((row) => row.vehicle_id === vehicle.id), vehicleTrips = trips.filter((row) => row.vehicle_id === vehicle.id); return <details key={String(vehicle.id)} className="fleet-register__row"><summary><span className="fleet-register__icon"><CarFront size={21} /></span><div><strong>{String(vehicle.registration_number)}</strong><small>{String(vehicle.make ?? "")} {String(vehicle.model ?? "")} · {String(vehicle.vehicle_type)}</small></div><span className="status-chip">{String(vehicle.status)}</span><ChevronDown size={16} /></summary><div className="fleet-register__details"><p>Przebieg: {number(vehicle.current_mileage)} km · paliwo: {money(vehicleFuel.reduce((sum, row) => sum + Number(row.gross_amount ?? 0), 0))} · serwis: {money(vehicleService.reduce((sum, row) => sum + Number(row.cost ?? 0), 0))} · trasy: {number(vehicleTrips.reduce((sum, row) => sum + Number(row.distance_km ?? 0), 0))} km</p><SimpleList>{vehicleDocs.map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.valid_until ?? "—")} title={String(row.document_type)} detail={String(row.number ?? "bez numeru")} />)}</SimpleList>{canWrite ? <div className="ops-inline-actions">{vehicleService.filter((row) => row.status === "open").map((row) => <InlineAction key={String(row.id)} entity="service_close" success="Serwis został zamknięty." fields={{ serviceId: String(row.id), closedAt: today(), cost: String(row.cost ?? "") }} label={`Zamknij serwis: ${String(row.service_type)}`} submit={submit} pending={pending} />)}<InlineAction entity="vehicle_status" success="Status pojazdu został zmieniony." fields={{ vehicleId: String(vehicle.id), status: vehicle.status === "active" ? "inactive" : "active" }} label={vehicle.status === "active" ? "Wycofaj z użycia" : "Przywróć do użycia"} submit={submit} pending={pending} danger={vehicle.status === "active"} /></div> : null}</div></details>; })}{!visibleVehicles.length ? <Empty /> : null}</div></Panel>
  </>;
}

function Reports({ data, canWrite, pending, submit, query }: { data: Data; canWrite: boolean; pending: boolean; submit: SubmitFactory; query: string }) {
  const definitions = data.definitions ?? [], runs = data.runs ?? [], snapshots = data.snapshots ?? [], projects = data.projects ?? [];
  const projectNames = new Map(projects.map((row) => [String(row.id), String(row.name)]));
  const visibleDefinitions = definitions.filter((row) => matches(row, query)), visibleSnapshots = snapshots.filter((row) => matches(row, query));
  const forms = [
    { title: "Nowa definicja raportu", entity: "report_definition", success: "Definicja została zapisana.", fields: [{ name: "name", label: "Nazwa", required: true }, { name: "reportType", label: "Typ", type: "select" as const, options: [["management", "Zarządczy firmy"], ["project", "Inwestycja"], ["finance", "Finansowy"], ["hr", "Kadrowy"], ["warehouse", "Magazynowy"], ["fleet", "Flotowy"]] as Array<[string, string]> }, { name: "projectId", label: "Inwestycja", rows: projects, placeholder: "Cała firma" }, { name: "scheduleRule", label: "Cykl", type: "select" as const, options: [["manual", "Ręcznie"], ["weekly", "Tygodniowo"], ["monthly", "Miesięcznie"]] as Array<[string, string]> }] },
    { title: "Generuj zamknięty snapshot", entity: "report_generate", success: "Raport został zamknięty.", fields: [{ name: "definitionId", label: "Definicja", rows: definitions, required: true }, { name: "periodStart", label: "Okres od", type: "date" as const }, { name: "periodEnd", label: "Okres do", type: "date" as const, defaultValue: today() }] }
  ];
  return <><section className="ops-metrics"><Metric icon={<FileBarChart />} title="Definicje raportów" value={definitions.length} caption="Kliknij: lista definicji"><SimpleList>{visibleDefinitions.map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.report_type)} title={String(row.name)} detail={String(row.schedule_rule ?? "ręcznie")} />)}</SimpleList></Metric><Metric icon={<Save />} title="Snapshoty" value={snapshots.length} caption="Kliknij: historia"><SimpleList>{visibleSnapshots.slice(0, 10).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.closed_at ?? row.created_at)} title="Snapshot raportu" detail="Niezmienna historia danych" />)}</SimpleList></Metric><Metric icon={<CalendarClock />} title="Uruchomienia" value={runs.length} caption="Kliknij: wykonania"><SimpleList>{runs.filter((row) => matches(row, query)).slice(0, 10).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.created_at)} title={String(row.status)} detail={`${String(row.period_start ?? "—")}–${String(row.period_end ?? "—")}`} />)}</SimpleList></Metric><Metric icon={<AlertTriangle />} title="Błędy" value={runs.filter((row) => row.status === "error").length} caption="Kliknij: wymagają reakcji"><SimpleList>{runs.filter((row) => row.status === "error" && matches(row, query)).map((row) => <ListRow key={String(row.id)} id={String(row.id)} top={String(row.created_at)} title="Błąd raportu" detail={String(row.id)} />)}</SimpleList></Metric></section>
    {canWrite ? <section className="ops-form-grid">{forms.map((form) => <RecordForm key={form.entity} {...form} submit={submit} pending={pending} />)}</section> : null}
    <Panel title="Zamknięte snapshoty danych" eyebrow="Historia raportów" meta={`${visibleSnapshots.length} raportów`} wide open><div className="report-snapshot-grid">{visibleSnapshots.map((snapshot) => { const dataSnapshot = snapshot.data_snapshot as { scope?: { project_id?: string | null }; period?: { start?: string | null; end?: string | null }; portfolio?: { projects?: number; documents?: number }; finance?: { sales_gross?: number; gross_result?: number } } | undefined, narrative = snapshot.narrative as Record<string, string> | undefined; const projectId = dataSnapshot?.scope?.project_id ?? String(snapshot.project_id ?? ""); return <article key={String(snapshot.id)}><FileBarChart size={21} /><small>{String(snapshot.closed_at ?? snapshot.created_at ?? "")}</small><h3>{narrative?.title ?? "Raport firmy"}</h3><p>{narrative?.summary ?? "Snapshot zatwierdzonych danych."}</p><p className="report-snapshot-scope">Zakres: {projectId ? projectNames.get(projectId) ?? "Inwestycja" : "cała firma"} · {dataSnapshot?.period?.start ?? "początek"}–{dataSnapshot?.period?.end ?? "dzisiaj"}</p><dl><div><dt>Inwestycje</dt><dd>{dataSnapshot?.portfolio?.projects ?? 0}</dd></div><div><dt>Dokumenty</dt><dd>{dataSnapshot?.portfolio?.documents ?? 0}</dd></div><div><dt>Sprzedaż</dt><dd>{money(dataSnapshot?.finance?.sales_gross)}</dd></div><div><dt>Wynik brutto</dt><dd>{money(dataSnapshot?.finance?.gross_result)}</dd></div></dl><div className="ops-inline-actions"><a className="secondary-button" href={`/api/company/reports/${String(snapshot.id)}?format=csv`}>Eksport CSV</a><a className="secondary-button" href={`/api/company/reports/${String(snapshot.id)}?format=json`}>Eksport JSON</a></div></article>; })}{!visibleSnapshots.length ? <Empty /> : null}</div></Panel>
  </>;
}

export function CompanyOperationsWorkspace({ workspaceId, kind, data, canWrite, referenceDate }: Props) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string | null>(null), [error, setError] = useState<string | null>(null), [query, setQuery] = useState("");
  const submit: SubmitFactory = (entity, success) => (event) => {
    event.preventDefault();
    const form = event.currentTarget, payload = Object.fromEntries(new FormData(form).entries());
    setMessage(null); setError(null);
    startTransition(async () => {
      const response = await fetch("/api/company/records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, entity, payload }) });
      const result = await response.json() as { error?: string };
      if (!response.ok) { setError(result.error ?? "Nie udało się zapisać danych."); return; }
      form.reset(); setMessage(success); router.refresh();
    });
  };
  return <div className="ops-workspace"><SearchBar value={query} onChange={setQuery} kind={kind} />{!canWrite ? <div className="pw-protected-data"><AlertTriangle size={19} /><div><strong>Dostęp tylko do odczytu</strong><p>Administrator może nadać uprawnienie zapisu.</p></div></div> : null}{message ? <p className="ops-feedback ops-feedback--success">{message}</p> : null}{error ? <p className="ops-feedback ops-feedback--error">{error}</p> : null}{kind === "finance" ? <Finance workspaceId={workspaceId} data={data} canWrite={canWrite} pending={pending} submit={submit} query={query} /> : null}{kind === "hr" ? <Hr data={data} canWrite={canWrite} pending={pending} submit={submit} query={query} referenceDate={referenceDate} /> : null}{kind === "warehouse" ? <Warehouse workspaceId={workspaceId} data={data} canWrite={canWrite} pending={pending} submit={submit} query={query} /> : null}{kind === "fleet" ? <Fleet data={data} canWrite={canWrite} pending={pending} submit={submit} query={query} referenceDate={referenceDate} /> : null}{kind === "reports" ? <Reports data={data} canWrite={canWrite} pending={pending} submit={submit} query={query} /> : null}</div>;
}
