"use client";

import { useEffect, useMemo, useState, useTransition, type ComponentProps, type FormEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Boxes, BrainCircuit, PackageCheck, PlugZap, RotateCcw, ScanLine, Send, Truck, Undo2 } from "lucide-react";
import { WarehouseWorkspace300 } from "@/components/company/warehouse-workspace-300";
import { enqueueWarehouseScan, flushWarehouseScans, pendingWarehouseScans } from "@/lib/warehouse/offline-scan-queue";
import styles from "./warehouse-market-400.module.css";

type Props = ComponentProps<typeof WarehouseWorkspace300>;
type Row = Record<string, unknown>;
type Mode = "operations" | "wms" | "planning" | "suppliers" | "shipping" | "integrations";
type Field = { name: string; label: string; type?: "text" | "number" | "date" | "datetime-local" | "textarea" | "select"; required?: boolean; options?: Array<[string,string]>; rows?: Row[]; rowLabel?: (row: Row)=>string; full?: boolean; placeholder?: string };

const text=(v:unknown,f="—")=>v===null||v===undefined||v===""?f:String(v);
const num=(v:unknown,d=1)=>new Intl.NumberFormat("pl-PL",{maximumFractionDigits:d}).format(Number(v??0)||0);
const money=(v:unknown)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:2}).format(Number(v??0)||0);
const date=(v:unknown)=>{if(!v)return"—";const x=new Date(String(v));return Number.isNaN(x.getTime())?String(v):new Intl.DateTimeFormat("pl-PL").format(x)};
const itemLabel=(r:Row)=>`${text(r.name)}${r.sku?` · ${text(r.sku)}`:""}`;
const projectLabel=(r:Row)=>text(r.name);
const employeeLabel=(r:Row)=>`${text(r.first_name,"")} ${text(r.last_name,"")}`.trim()||text(r.employee_number);
const statusTone=(v:unknown)=>["available","active","done","delivered","approved","ready","executed"].includes(String(v))?styles.good:["blocked","critical","error","expired","rejected","exception"].includes(String(v))?styles.bad:styles.warn;

function Kpi({label,value}:{label:string;value:ReactNode}){return <div className={styles.kpi}><small>{label}</small><strong>{value}</strong></div>}
function Badge({children,tone=styles.badge}:{children:ReactNode;tone?:string}){return <span className={tone}>{children}</span>}
function Panel({title,kicker,children,wide=false}:{title:string;kicker?:string;children:ReactNode;wide?:boolean}){return <section className={`${styles.panel} ${wide?styles.wide:""}`}><div className={styles.head}>{kicker?<small>{kicker}</small>:null}<h2>{title}</h2></div>{children}</section>}
function MiniForm({title,action,fields,pending,disabled,onSubmit}:{title:string;action:string;fields:Field[];pending:boolean;disabled?:boolean;onSubmit:(action:string,e:FormEvent<HTMLFormElement>)=>void}){
  return <details className={styles.form}><summary>{title}</summary><form onSubmit={e=>onSubmit(action,e)}><div className={styles.fields}>{fields.map(f=><label key={f.name} className={f.full?styles.full:undefined}><span>{f.label}</span>{f.type==="textarea"?<textarea name={f.name} required={f.required} placeholder={f.placeholder}/>:f.options||f.rows||f.type==="select"?<select name={f.name} required={f.required}><option value="">Wybierz</option>{f.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}{f.rows?.map(r=><option key={String(r.id)} value={String(r.id)}>{f.rowLabel?f.rowLabel(r):text(r.name??r.id)}</option>)}</select>:<input name={f.name} type={f.type??"text"} required={f.required} placeholder={f.placeholder} step={f.type==="number"?"any":undefined}/>}</label>)}</div><button className={styles.primary} disabled={disabled||pending}>{pending?"Zapisywanie…":"Zapisz"}</button></form></details>
}

export function WarehouseMarket400(props:Props){
  const router=useRouter();const [pending,startTransition]=useTransition();const [mode,setMode]=useState<Mode>("operations");const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [issuedSecret,setIssuedSecret]=useState<string|null>(null);const [scanCode,setScanCode]=useState("");const [queued,setQueued]=useState(0);
  const data=props.data as Record<string,unknown>;
  const items=((data.warehousePlanningItems??data.catalogItems??data.items)??[]) as Row[],warehouses=(data.warehouses??[]) as Row[],projects=(data.projects??[]) as Row[],employees=(data.employees??[]) as Row[],counterparties=(data.counterparties??[]) as Row[];
  const locations=((data.warehouseLocations400??data.warehouseLocations)??[]) as Row[],lots=(data.stockLots??[]) as Row[],units=(data.logisticUnits??[]) as Row[],tasks=(data.warehouseTasks400??[]) as Row[],scores=(data.supplierScores400??[]) as Row[];
  const returns=(data.warehouseReturns400??[]) as Row[],forecasts=(data.warehouseForecasts400??[]) as Row[],readiness=(data.materialReadiness400??[]) as Row[],recommendations=(data.warehouseAiRecommendations400??[]) as Row[],integrations=(data.warehouseIntegrations400??[]) as Row[],events=(data.warehouseDeviceEvents400??[]) as Row[],shipments=(data.warehouseShipments400??[]) as Row[],summary=(data.warehouse400Summary??{}) as Row;
  const itemById=useMemo(()=>new Map(items.map(r=>[String(r.id),r])),[items]);const projectById=useMemo(()=>new Map(projects.map(r=>[String(r.id),r])),[projects]);const counterpartyById=useMemo(()=>new Map(counterparties.map(r=>[String(r.id),r])),[counterparties]);
  const latestReadiness=useMemo(()=>{const m=new Map<string,Row>();readiness.forEach(r=>{const id=String(r.project_id);if(!m.has(id))m.set(id,r)});return [...m.values()]},[readiness]);
  const modes:Array<[Mode,string,ReactNode]>=[["operations","Operacje",<Boxes size={14} key="o"/>],["wms","WMS i partie",<PackageCheck size={14} key="w"/>],["planning","Planowanie AI",<BrainCircuit size={14} key="p"/>],["suppliers","Dostawcy i zwroty",<Undo2 size={14} key="r"/>],["shipping","Wysyłki",<Truck size={14} key="s"/>],["integrations","Skanery i integracje",<PlugZap size={14} key="i"/>]];

  useEffect(()=>{setQueued(pendingWarehouseScans().length);const online=()=>{void flushWarehouseScans(props.workspaceId).then(r=>{setQueued(r.pending);if(r.sent){setMessage(`Wysłano ${r.sent} skanów zapisanych offline.`);router.refresh();}})};window.addEventListener("online",online);return()=>window.removeEventListener("online",online)},[props.workspaceId,router]);
  const run=(action:string,payload:Record<string,unknown>)=>{setMessage(null);setError(null);setIssuedSecret(null);startTransition(async()=>{try{const response=await fetch("/api/company/warehouse-market",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId:props.workspaceId,action,payload})});const out=await response.json().catch(()=>({})) as {error?:string;issuedSecret?:string;result?:{requiresHumanApproval?:boolean}};if(!response.ok)throw new Error(out.error??"Operacja nie powiodła się.");if(out.issuedSecret)setIssuedSecret(out.issuedSecret);setMessage(out.result?.requiresHumanApproval?"Utworzono wyłącznie szkic zamówienia. Oczekuje na zatwierdzenie człowieka.":"Operacja została wykonana.");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Operacja nie powiodła się.")}})};
  const submit=(action:string,e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(action,Object.fromEntries(new FormData(e.currentTarget).entries()))};
  const queueScan=async()=>{const code=scanCode.trim();if(!code)return;const row=enqueueWarehouseScan({code});setScanCode("");setQueued(pendingWarehouseScans().length);if(typeof navigator!=="undefined"&&navigator.onLine){const result=await flushWarehouseScans(props.workspaceId);setQueued(result.pending);if(result.sent){setMessage(`Skan ${code} zapisano w kolejce zdarzeń Magazynu.`);router.refresh();}}else setMessage(`Skan ${row.code} zapisano offline. Zostanie wysłany po odzyskaniu połączenia.`)};

  return <div className={styles.shell} data-warehouse-market="4.0">
    <nav className={styles.modes} aria-label="Magazyn 4.0">{modes.map(([id,label,icon])=><button type="button" key={id} className={`${styles.mode} ${mode===id?styles.active:""}`} onClick={()=>setMode(id)}>{icon}{label}</button>)}</nav>
    {mode!=="operations"?<div className={styles.kpis}><Kpi label="Otwarte zadania WMS" value={text(summary.openTasks,String(tasks.filter(r=>!["done","cancelled"].includes(String(r.status))).length))}/><Kpi label="Partie ≤30 dni" value={text(summary.expiringLots30,String(lots.filter(r=>r.expiry_date).length))}/><Kpi label="Zwroty / RMA" value={text(summary.openReturns,String(returns.length))}/><Kpi label="Aktywne wysyłki" value={text(summary.activeShipments,String(shipments.length))}/><Kpi label="Ryzyko materiałowe" value={text(summary.projectsMaterialRisk,String(latestReadiness.filter(r=>Number(r.score)<80).length))}/><Kpi label="AI Material Planner" value={text(summary.aiRecommendations,String(recommendations.filter(r=>r.status==="new").length))}/></div>:null}
    {message?<div className={`${styles.feedback} ${styles.success}`}>{message}</div>:null}{error?<div className={`${styles.feedback} ${styles.error}`}>{error}</div>:null}
    {issuedSecret?<div className={styles.guard}><strong>Sekret webhooka — wyświetlany tylko teraz.</strong><code>{issuedSecret}</code><span>Endpoint: /api/integrations/warehouse/ingest?integrationId=ID</span></div>:null}
    {mode==="operations"?<WarehouseWorkspace300 {...props}/>:null}

    {mode==="wms"?<div className={styles.grid}>
      <Panel title="Zadania WMS" kicker="Put-away · picking · count · move · pack · cross-dock">
        {props.canWrite?<MiniForm title="Nowe zadanie" action="task_create" pending={pending} onSubmit={submit} fields={[{name:"warehouseId",label:"Magazyn",rows:warehouses,required:true},{name:"taskType",label:"Typ",type:"select",options:[["putaway","Put-away"],["pick","Picking"],["replenish_pickface","Uzupełnij pick-face"],["crossdock","Cross-dock"],["count","Inwentaryzacja"],["move","Przesunięcie"],["pack","Pakowanie"],["dispatch","Wydanie"],["return_inspection","Kontrola zwrotu"]],required:true},{name:"priority",label:"Priorytet",type:"number"},{name:"stockItemId",label:"Kartoteka",rows:items,rowLabel:itemLabel},{name:"quantity",label:"Ilość",type:"number"},{name:"sourceLocationId",label:"Z lokalizacji",rows:locations,rowLabel:r=>`${text(r.code)} · ${text(r.name)}`},{name:"targetLocationId",label:"Do lokalizacji",rows:locations,rowLabel:r=>`${text(r.code)} · ${text(r.name)}`},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"assignedEmployeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel},{name:"instructions",label:"Instrukcja",type:"textarea",full:true}]}/>:null}
        <div className={styles.table}><table><thead><tr><th>Typ</th><th>Materiał</th><th>Lokalizacja</th><th>Osoba</th><th>Status</th><th>Akcja</th></tr></thead><tbody>{tasks.slice(0,40).map(r=><tr key={String(r.id)}><td>{text(r.task_type)}</td><td>{itemLabel(itemById.get(String(r.stock_item_id))??{})}</td><td>{text(r.source_location_id)} → {text(r.target_location_id)}</td><td>{employeeLabel(employees.find(e=>String(e.id)===String(r.assigned_employee_id))??{})}</td><td><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></td><td>{props.canWrite&&!['done','cancelled'].includes(String(r.status))?<button className={styles.secondary} onClick={()=>run("task_status",{taskId:r.id,status:"done"})}>Zakończ</button>:"—"}</td></tr>)}</tbody></table></div>
      </Panel>
      <Panel title="Partie LOT / FEFO" kicker="Ważność, kwarantanna, koszt i pochodzenie">
        <div className={styles.cards}>{lots.slice(0,30).map(r=><div className={styles.card} key={String(r.id)}><h3>{itemLabel(itemById.get(String(r.stock_item_id))??{})}</h3><p>LOT {text(r.lot_number)} · {num(r.remaining_quantity)} · ważność {date(r.expiry_date)}</p><p><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge>{r.unit_cost?` · ${money(r.unit_cost)}`:""}</p>{props.canWrite&&String(r.status)==="available"?<button className={styles.secondary} onClick={()=>run("lot_status",{lotId:r.id,status:"quarantine"})}>Kwarantanna</button>:null}</div>)}</div>
      </Panel>
      <Panel title="Palety / SSCC / jednostki logistyczne" kicker="Kontener → paleta → karton">
        {props.canWrite?<MiniForm title="Nowa jednostka logistyczna" action="logistic_unit_create" pending={pending} onSubmit={submit} fields={[{name:"warehouseId",label:"Magazyn",rows:warehouses,required:true},{name:"locationId",label:"Lokalizacja",rows:locations,rowLabel:r=>`${text(r.code)} · ${text(r.name)}`},{name:"unitType",label:"Typ",type:"select",options:[["pallet","Paleta"],["carton","Karton"],["container","Kontener"],["bundle","Paczka"],["other","Inne"]]},{name:"sscc",label:"SSCC"},{name:"labelCode",label:"Kod etykiety"},{name:"grossWeightKg",label:"Masa kg",type:"number"},{name:"volumeM3",label:"Objętość m³",type:"number"}]}/>:null}
        <div className={styles.cards}>{units.slice(0,24).map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.unit_type)} · {text(r.sscc??r.label_code)}</h3><p>{text(r.location_id)} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p></div>)}</div>
      </Panel>
    </div>:null}

    {mode==="planning"?<div className={styles.grid}>
      <Panel title="AI Material Planner" kicker="ABC/XYZ · prognoza · min/max · Project Material Readiness" wide>
        <div className={styles.guard}><strong>Guardrail zakupowy.</strong><span>Autonomous Replenishment nie wysyła zamówienia do dostawcy. Może utworzyć wyłącznie szkic PO, który wymaga osobnego zatwierdzenia człowieka.</span></div>
        {props.canWrite?<button className={styles.primary} onClick={()=>run("refresh_intelligence",{},"Odświeżono")}> <RotateCcw size={14}/> Przelicz Digital Worker</button>:null}
        <div className={styles.readiness}>{latestReadiness.slice(0,20).map(r=><div className={styles.card} key={String(r.id)}><h3>{projectLabel(projectById.get(String(r.project_id))??{})}</h3><strong>{num(r.score)}%</strong><p>{text(r.ready_lines,"0")}/{text(r.required_lines,"0")} pozycji gotowych · braki {text(r.shortage_lines,"0")}</p></div>)}</div>
      </Panel>
      <Panel title="Rekomendacje AI" kicker="Decyzje o ruchu i zakupie pozostają kontrolowane">
        <div className={styles.cards}>{recommendations.slice(0,30).map(r=>{const payload=(r.action_payload&&typeof r.action_payload==="object"?r.action_payload:{}) as Row;const stockItemId=text(payload.stockItemId??r.stock_item_id,"");return <div className={styles.card} key={String(r.id)}><h3>{text(r.title)}</h3><p>{text(r.description)}</p><p><Badge tone={statusTone(r.severity)}>{text(r.severity)}</Badge> · {text(r.recommendation_type)}</p><div className={styles.actions}>{props.canApprove&&String(r.status)==="new"?<><button className={styles.secondary} onClick={()=>run("recommendation_status",{recommendationId:r.id,status:"accepted"})}>Akceptuj sygnał</button><button className={styles.secondary} onClick={()=>run("recommendation_status",{recommendationId:r.id,status:"dismissed"})}>Odrzuć</button></>:null}{props.canApprove&&stockItemId&&String(r.recommendation_type)==="shortage"?<button className={styles.primary} onClick={()=>run("autonomous_replenishment",{stockItemId})}>Utwórz szkic PO</button>:null}</div></div>})}</div>
      </Panel>
      <Panel title="Strategia kartotek" kicker="FIFO / FEFO / LIFO + polityka zamawiania">
        {props.canWrite?<MiniForm title="Zmień planowanie kartoteki" action="item_planning_update" pending={pending} onSubmit={submit} fields={[{name:"stockItemId",label:"Kartoteka",rows:items,rowLabel:itemLabel,required:true},{name:"stockStrategy",label:"Rotacja",type:"select",options:[["fifo","FIFO"],["fefo","FEFO"],["lifo","LIFO"]]},{name:"reorderPolicy",label:"Polityka",type:"select",options:[["manual","Ręczna"],["minmax","Min/Max"],["forecast","Prognoza"],["project_demand","Popyt inwestycji"]]},{name:"leadTimeDays",label:"Lead time [dni]",type:"number"},{name:"serviceLevelPct",label:"Service level %",type:"number"},{name:"dynamicMinStock",label:"Min dynamiczny",type:"number"},{name:"dynamicMaxStock",label:"Max dynamiczny",type:"number"},{name:"shelfLifeDays",label:"Shelf-life [dni]",type:"number"},{name:"gtin",label:"GTIN"},{name:"lotTracking",label:"Śledź LOT",type:"select",options:[["true","Tak"],["false","Nie"]]},{name:"expiryTracking",label:"Śledź ważność",type:"select",options:[["true","Tak"],["false","Nie"]]},{name:"gs1Enabled",label:"GS1",type:"select",options:[["true","Tak"],["false","Nie"]]}]}/>:null}
        <div className={styles.table}><table><thead><tr><th>Kartoteka</th><th>ABC/XYZ</th><th>Strategia</th><th>Min/Max</th><th>Prognoza</th></tr></thead><tbody>{items.slice(0,50).map(r=>{const f=forecasts.find(x=>String(x.stock_item_id)===String(r.id));return <tr key={String(r.id)}><td>{itemLabel(r)}</td><td>{text(r.abc_class)}/{text(r.xyz_class)}</td><td>{text(r.stock_strategy)} · {text(r.reorder_policy)}</td><td>{num(r.dynamic_min_stock)} / {num(r.dynamic_max_stock)}</td><td>{f?num(f.forecast_quantity):"—"}</td></tr>})}</tbody></table></div>
      </Panel>
    </div>:null}

    {mode==="suppliers"?<div className={styles.grid}>
      <Panel title="AI Supplier Score" kicker="Cena · terminowość · jakość · zwroty">
        <div className={styles.table}><table><thead><tr><th>Dostawca</th><th>Ocena</th><th>Cena</th><th>Dostawy</th><th>Jakość</th><th>Próba</th></tr></thead><tbody>{scores.slice(0,40).map(r=><tr key={String(r.id)}><td>{text(counterpartyById.get(String(r.counterparty_id))?.name)}</td><td><strong>{num(r.overall_score)}</strong></td><td>{num(r.price_score)}</td><td>{num(r.delivery_score)}</td><td>{num(r.quality_score)}</td><td>{text(r.sample_count)}</td></tr>)}</tbody></table></div>
      </Panel>
      <Panel title="Zwroty / RMA / reklamacje" kicker="Dostawca · klient · wewnętrzne · gwarancja">
        {props.canWrite?<MiniForm title="Nowy zwrot / RMA" action="return_create" pending={pending} onSubmit={submit} fields={[{name:"returnNumber",label:"Numer"},{name:"returnType",label:"Typ",type:"select",options:[["supplier","Do dostawcy"],["customer","Od klienta"],["internal","Wewnętrzny"],["warranty","Gwarancja"]]},{name:"counterpartyId",label:"Kontrahent",rows:counterparties,rowLabel:r=>text(r.name)},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"rmaNumber",label:"RMA"},{name:"requestedAt",label:"Data",type:"date"},{name:"reason",label:"Powód",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{returns.slice(0,30).map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.return_number)} · {text(r.return_type)}</h3><p>{text(counterpartyById.get(String(r.counterparty_id))?.name)} · {date(r.requested_at)}</p><p><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge> {r.rma_number?`· RMA ${text(r.rma_number)}`:""}</p>{props.canApprove&&String(r.status)==="submitted"?<button className={styles.secondary} onClick={()=>run("return_status",{returnId:r.id,status:"approved"})}>Zatwierdź</button>:null}</div>)}</div>
      </Panel>
    </div>:null}

    {mode==="shipping"?<div className={styles.grid}>
      <Panel title="Wysyłki i kurierzy" kicker="Inbound / outbound · tracking · status" wide>
        {props.canWrite?<MiniForm title="Nowa przesyłka" action="shipment_create" pending={pending} onSubmit={submit} fields={[{name:"warehouseId",label:"Magazyn",rows:warehouses,required:true},{name:"shipmentNumber",label:"Numer przesyłki"},{name:"direction",label:"Kierunek",type:"select",options:[["outbound","Wychodząca"],["inbound","Przychodząca"]]},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"counterpartyId",label:"Kontrahent",rows:counterparties,rowLabel:r=>text(r.name)},{name:"carrier",label:"Przewoźnik"},{name:"serviceLevel",label:"Usługa"},{name:"trackingNumber",label:"Tracking"},{name:"plannedAt",label:"Planowany termin",type:"datetime-local"},{name:"note",label:"Notatka",type:"textarea",full:true}]}/>:null}
        <div className={styles.table}><table><thead><tr><th>Numer</th><th>Kierunek</th><th>Przewoźnik</th><th>Tracking</th><th>Inwestycja</th><th>Status</th><th>Akcja</th></tr></thead><tbody>{shipments.slice(0,50).map(r=><tr key={String(r.id)}><td>{text(r.shipment_number)}</td><td>{text(r.direction)}</td><td>{text(r.carrier)}</td><td>{text(r.tracking_number)}</td><td>{projectLabel(projectById.get(String(r.project_id))??{})}</td><td><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></td><td>{props.canApprove&&String(r.status)==="ready"?<button className={styles.secondary} onClick={()=>run("shipment_status",{shipmentId:r.id,status:"dispatched"})}>Wydaj</button>:"—"}</td></tr>)}</tbody></table></div>
      </Panel>
    </div>:null}

    {mode==="integrations"?<div className={styles.grid}>
      <Panel title="Skaner mobilny offline" kicker="Kolejka lokalna → synchronizacja po odzyskaniu sieci">
        <div className={styles.scan}><ScanLine size={22}/><input value={scanCode} onChange={e=>setScanCode(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void queueScan()}}} placeholder="Zeskanuj / wpisz GTIN, SKU, SSCC lub kod lokalizacji"/><button className={styles.primary} onClick={()=>void queueScan()} disabled={!scanCode.trim()}>Dodaj skan</button></div><p>Oczekuje offline: <strong>{queued}</strong>. Skan nie zmienia stanu magazynowego — tworzy zdarzenie wymagające potwierdzonego procesu/ruchu.</p>{queued>0?<button className={styles.secondary} onClick={()=>void flushWarehouseScans(props.workspaceId).then(r=>{setQueued(r.pending);setMessage(`Wysłano ${r.sent}; pozostało ${r.pending}.`);router.refresh()})}><Send size={14}/> Synchronizuj teraz</button>:null}
      </Panel>
      <Panel title="RFID / wagi / automatyka / WMS" kicker="Uniwersalny webhook urządzeń">
        {props.canWrite?<MiniForm title="Nowa integracja" action="integration_create" pending={pending} onSubmit={submit} fields={[{name:"provider",label:"Provider",placeholder:"generic / RFID / waga / automat"},{name:"name",label:"Nazwa",required:true},{name:"mode",label:"Tryb",type:"select",options:[["webhook","Webhook"],["poll","Polling"],["file","Plik"],["manual","Ręczny"]]},{name:"capabilities",label:"Możliwości",placeholder:"scan,rfid,weight,automation,shipment_status"},{name:"notes",label:"Notatki",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{integrations.map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.name)} · {text(r.provider)}</h3><p><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge> · ostatnio {date(r.last_sync_at)}</p><div className={styles.actions}>{props.canWrite?<button className={styles.secondary} onClick={()=>run("integration_rotate_secret",{integrationId:r.id})}>Obróć sekret</button>:null}{props.canApprove&&String(r.status)!=="disabled"?<button className={styles.secondary} onClick={()=>run("integration_disable",{integrationId:r.id})}>Wyłącz</button>:null}</div></div>)}</div>
      </Panel>
      <Panel title="Ostatnie zdarzenia urządzeń" kicker="Brak ślepych ruchów magazynowych" wide>
        <div className={styles.table}><table><thead><tr><th>Czas</th><th>Typ</th><th>Kod/źródło</th><th>Kartoteka</th><th>Lokalizacja</th><th>Przetworzone</th></tr></thead><tbody>{events.slice(0,50).map(r=><tr key={String(r.id)}><td>{date(r.occurred_at)}</td><td>{text(r.event_type)}</td><td>{text(r.external_event_id)}</td><td>{itemLabel(itemById.get(String(r.stock_item_id))??{})}</td><td>{text(r.location_id)}</td><td>{r.processed?"Tak":"Nie — wymaga procesu"}</td></tr>)}</tbody></table></div>
      </Panel>
    </div>:null}
  </div>
}
