import type { AutopilotDecision, AutopilotMission, AutopilotPriority, InstallationMatrixItem, InvestmentAutopilotSnapshot, ReconciliationFinding } from "@/lib/investments/autopilot";
import { changeConsequences } from "@/lib/investments/autopilot";

type Json=Record<string,unknown>;
function array(value:unknown):Json[]{return Array.isArray(value)?value as Json[]:[];}
function record(value:unknown):Json{return value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{};}
function clean(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[łŁ]/g,"l").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function number(value:unknown){const n=Number(value??0);return Number.isFinite(n)?n:0;}
function priorityWeight(priority:AutopilotPriority){return priority==="critical"?0:priority==="high"?1:priority==="medium"?2:3;}
function dueWeight(value:string|null){if(!value)return Number.MAX_SAFE_INTEGER;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:Number.MAX_SAFE_INTEGER;}
function riskPriority(value:unknown):AutopilotPriority{const v=clean(value);if(v.includes("critical")||v.includes("kryty"))return"critical";if(v.includes("high")||v.includes("wysok"))return"high";if(v.includes("medium")||v.includes("sred"))return"medium";return"low";}
function str(value:unknown){return value==null?"":String(value);}

function installationRows(value:unknown):InstallationMatrixItem[]{return array(value).map(row=>{const materials=number(row.materials),devices=number(row.devices),boqItems=number(row.boqItems),requests=number(row.materialRequests),approvedRequests=number(row.approvedMaterialRequests),schedule=number(row.scheduleActivities),protocols=number(row.protocolsRequired),protocolsClosed=number(row.protocolsClosed),evidence=number(row.evidenceRequired),evidenceComplete=number(row.evidenceComplete);const readiness=Math.max(0,Math.min(100,(materials+devices+boqItems>0?20:0)+(boqItems>0?20:0)+(requests===0?(materials+devices?10:20):Math.round(20*approvedRequests/requests))+(schedule>0?20:0)+(protocols===0?20:Math.round(20*protocolsClosed/protocols))-(evidence?Math.round(10*(1-evidenceComplete/evidence)):0)));const state:InstallationMatrixItem["state"]=readiness>=80?"ready":readiness>=50?"attention":"blocked";return{name:str(row.name)||"Zakres ogólny",wbsCodes:Array.isArray(row.wbsCodes)?row.wbsCodes.map(str):[],materials,devices,boqItems,materialRequests:requests,approvedMaterialRequests:approvedRequests,scheduleActivities:schedule,protocolsRequired:protocols,protocolsClosed,evidenceRequired:evidence,evidenceComplete,readiness,state};}).sort((a,b)=>a.readiness-b.readiness||a.name.localeCompare(b.name,"pl"));}

function reconciliation(value:unknown):InvestmentAutopilotSnapshot["reconciliation"]{const row=record(value),acceptedWorkValue=number(row.acceptedWorkValue),salesNet=number(row.salesNet),purchaseNet=number(row.purchaseNet),warehouseDocuments=number(row.warehouseDocuments),approvedMaterialRequests=number(row.approvedMaterialRequests),findings:ReconciliationFinding[]=[];
  if(acceptedWorkValue>0&&salesNet>acceptedWorkValue*1.12)findings.push({id:"sales-over-progress",severity:"high",source:"finance",title:"Sprzedaż wyprzedza odebrany przerób",description:`Sprzedaż netto ${Math.round(salesNet).toLocaleString("pl-PL")} zł jest wyższa niż wartość odebranego BOQ ${Math.round(acceptedWorkValue).toLocaleString("pl-PL")} zł. Zweryfikuj podstawę rozliczenia.`});
  if(acceptedWorkValue>50000&&salesNet<acceptedWorkValue*.72)findings.push({id:"progress-under-invoiced",severity:"medium",source:"finance",title:"Możliwy przerób do zafakturowania",description:"Wartość odebranych robót istotnie przewyższa sprzedaż przypisaną do inwestycji. Sprawdź rozliczenie częściowe."});
  if(approvedMaterialRequests>0&&warehouseDocuments===0)findings.push({id:"approved-without-warehouse",severity:"medium",source:"warehouse",title:"Zatwierdzone materiały bez ruchu magazynowego",description:"Są zaakceptowane wnioski materiałowe, ale inwestycja nie ma zatwierdzonego WZ/RW/MM."});
  for(const item of array(row.boqAnomalies)){const quantity=number(item.quantity),executed=number(item.quantity_executed),accepted=number(item.quantity_accepted),id=str(item.id);if(quantity>0&&executed>quantity+.001)findings.push({id:`boq-over-${id}`,severity:"high",source:"boq",title:`Wykonanie ponad BOQ: ${str(item.item_number)||"pozycja"}`,description:`${str(item.description)}: wykonano ${executed}, plan ${quantity} ${str(item.unit)}.`});if(accepted>executed+.001)findings.push({id:`boq-accept-${id}`,severity:"high",source:"boq",title:`Odbiór większy od wykonania: ${str(item.item_number)||"pozycja"}`,description:str(item.description)});}
  return{acceptedWorkValue,salesNet,purchaseNet,warehouseDocuments,findings:findings.slice(0,12)};
}

export function buildCompactAutopilotSnapshot(raw:Json,decisions:AutopilotDecision[],workspaceId:string,projectId:string,nowIso:string):InvestmentAutopilotSnapshot{
  const base=`/workspace/projects/${projectId}`,now=Date.parse(nowIso),missions:AutopilotMission[]=[];
  const requirements=array(raw.requirements),protocolRequirements=array(raw.protocolRequirements),protocols=array(raw.protocols),schedule=array(raw.scheduleActivities),impacts=array(raw.impacts),evidence=array(raw.evidence),findings=array(raw.findings),source=record(raw.source);
  for(const decision of decisions){if(!["review","error","new","processing"].includes(clean(decision.status)))continue;missions.push({id:`decision:${decision.id}`,title:decision.title,description:decision.detail,owner:"human",state:clean(decision.status)==="error"?"blocked":"todo",priority:clean(decision.status)==="error"?"critical":"high",category:"decision",actionLabel:"Podejmij decyzję",href:`/workspace/companies/${workspaceId}/ai-inbox`,sourceType:"ai_inbox",sourceId:decision.id,dueAt:null});}
  for(const impact of impacts){missions.push({id:`impact:${str(impact.id)}`,title:"Nowa rewizja wymaga decyzji",description:str(impact.summary),owner:"human",state:"blocked",priority:riskPriority(impact.risk_level),category:"change",actionLabel:"Sprawdź skutki zmiany",href:`${base}/control`,sourceType:"document_change_impact",sourceId:str(impact.id),dueAt:null});}
  for(const row of requirements){const type=clean(row.requirement_type),id=str(row.id),common={id:`requirement:${id}`,title:str(row.title),sourceType:"project_requirement",sourceId:id,dueAt:null} as const;if(type.includes("material"))missions.push({...common,description:str(row.description)||"Wymaganie materiałowe rozpoznane w dokumentacji.",owner:"ai",state:"ready",priority:"high",category:"material",actionLabel:"Przygotuj szkic WM",href:`${base}/requests`});else if(type.includes("work stage")||type.includes("work_stage"))missions.push({...common,description:str(row.description)||"Etap robót wykryty przez Brain.",owner:"ai",state:"ready",priority:"medium",category:"schedule",actionLabel:"Dodaj do planu",href:`${base}/schedule`});else if(type.includes("accept"))missions.push({...common,description:str(row.description)||"Warunek odbiorowy wymaga potwierdzenia.",owner:"field",state:"todo",priority:"high",category:"evidence",actionLabel:"Wykonaj / potwierdź",href:`${base}/protocols`});else missions.push({...common,description:str(row.description)||"Wymaganie wymaga decyzji koordynatora.",owner:"human",state:"todo",priority:"medium",category:"decision",actionLabel:"Zweryfikuj",href:`${base}/control`});}
  for(const requirement of protocolRequirements){const matching=protocols.find(protocol=>clean(protocol.protocol_type)===clean(requirement.protocol_type)||clean(protocol.title)===clean(requirement.title));if(matching&&["approved","archived","complete","completed"].includes(clean(matching.status)))continue;const id=str(requirement.id);missions.push({id:`protocol:${id}`,title:str(requirement.title),description:matching?"Szkic istnieje. Uzupełnij rzeczywisty wynik próby, datę, osoby i dowody.":"Octopus może przygotować szkic z danych projektowych. Wynik próby pozostaje po stronie człowieka.",owner:matching?"field":"ai",state:matching?"todo":"ready",priority:"high",category:"protocol",actionLabel:matching?"Wykonaj i uzupełnij":"Przygotuj szkic",href:`${base}/protocols`,sourceType:"protocol_requirement",sourceId:id,dueAt:null});}
  for(const row of evidence){const due=row.due_at?str(row.due_at):null,overdue=due?Date.parse(due)<now:false,id=str(row.id);missions.push({id:`evidence:${id}`,title:str(row.title),description:`Brakuje dowodu typu ${str(row.evidence_type)}.`,owner:"field",state:overdue?"blocked":"todo",priority:overdue?"critical":"medium",category:"evidence",actionLabel:"Dodaj dowód",href:`${base}/site`,sourceType:"evidence_requirement",sourceId:id,dueAt:due});}
  for(const row of schedule){const finish=row.planned_finish?str(row.planned_finish):null;if(!finish||Date.parse(finish)>=now)continue;const id=str(row.id);missions.push({id:`schedule:${id}`,title:`Opóźniona ścieżka krytyczna: ${str(row.title)}`,description:`Planowany koniec: ${finish}.`,owner:"human",state:"blocked",priority:"critical",category:"schedule",actionLabel:"Przelicz plan",href:`${base}/schedule`,sourceType:"schedule_activity",sourceId:id,dueAt:finish});}
  for(const row of findings){const id=str(row.id),critical=clean(row.severity)==="critical";missions.push({id:`finding:${id}`,title:str(row.title),description:str(row.description)||"Alert OctopusAI wymaga weryfikacji.",owner:"human",state:critical?"blocked":"todo",priority:critical?"critical":"high",category:"risk",actionLabel:"Zweryfikuj ryzyko",href:`${base}/brain`,sourceType:"ai_finding",sourceId:id,dueAt:null});}
  if(!Boolean(source.approved_boq)||number(source.boq_items)===0)missions.push({id:"source:boq",title:"Brak zatwierdzonej bazy BOQ",description:"Bez zatwierdzonego kosztorysu Octopus nie może wiarygodnie kontrolować przerobu, zakupów i rozliczeń.",owner:"human",state:"blocked",priority:"critical",category:"source",actionLabel:"Uzupełnij kosztorys",href:`${base}/cost-estimate`,sourceType:"boq",sourceId:projectId,dueAt:null});
  if(number(source.documents)===0)missions.push({id:"source:documents",title:"Brak dokumentacji źródłowej",description:"Wrzuć projekt, specyfikację, kosztorys i dokumenty kontraktowe, aby Brain mógł zbudować Project DNA.",owner:"human",state:"blocked",priority:"critical",category:"source",actionLabel:"Dodaj dokumenty",href:`${base}/documentation`,sourceType:"documents",sourceId:projectId,dueAt:null});
  const recon=reconciliation(raw.reconciliation);for(const finding of recon.findings.filter(row=>row.severity!=="info"))missions.push({id:`reconcile:${finding.id}`,title:finding.title,description:finding.description,owner:"human",state:finding.severity==="high"?"blocked":"todo",priority:finding.severity==="high"?"high":"medium",category:"finance",actionLabel:"Sprawdź zgodność",href:`${base}/control`,sourceType:`reconciliation_${finding.source}`,sourceId:finding.id,dueAt:null});
  const deduped=Array.from(new Map(missions.map(m=>[m.id,m])).values()).sort((a,b)=>priorityWeight(a.priority)-priorityWeight(b.priority)||dueWeight(a.dueAt)-dueWeight(b.dueAt)||a.title.localeCompare(b.title,"pl"));
  const aiCanDoCount=deduped.filter(row=>row.owner==="ai"&&row.state!=="done").length,humanDecisionCount=deduped.filter(row=>row.owner==="human"&&row.state!=="done").length,fieldActionCount=deduped.filter(row=>row.owner==="field"&&row.state!=="done").length,blockerCount=deduped.filter(row=>row.state==="blocked").length,criticalCount=deduped.filter(row=>row.priority==="critical").length,highCount=deduped.filter(row=>row.priority==="high").length,healthScore=Math.max(0,Math.min(100,100-criticalCount*10-highCount*4-Math.min(20,blockerCount*3)-Math.min(15,recon.findings.filter(row=>row.severity==="high").length*5)));
  const facts=number(source.facts),sourcedFacts=number(source.sourced_facts),changeRadar=impacts.map(row=>({id:str(row.id),summary:str(row.summary),riskLevel:str(row.risk_level),targetType:str(row.target_type),createdAt:str(row.created_at),consequences:changeConsequences(str(row.target_type),str(row.summary))})).sort((a,b)=>priorityWeight(riskPriority(a.riskLevel))-priorityWeight(riskPriority(b.riskLevel))||Date.parse(b.createdAt)-Date.parse(a.createdAt));
  return{healthScore,healthLabel:healthScore>=80?"stabilna":healthScore>=55?"uwaga":"ryzyko",missions:deduped,nextMission:deduped[0]??null,aiCanDoCount,humanDecisionCount,fieldActionCount,blockerCount,changeRadar,installations:installationRows(raw.installations),decisions:decisions.filter(row=>["review","error","new","processing"].includes(clean(row.status))).slice(0,12),reconciliation:recon,lineage:{documents:number(source.documents),readyDocuments:number(source.ready_documents),facts,sourcedFacts,sourceCoveragePercent:facts?Math.round(sourcedFacts/facts*100):0}};
}
