import { Activity, BrainCircuit, CheckCircle2, Gauge, TriangleAlert } from "lucide-react";

function percent(value:unknown){return `${Math.round(Number(value??0)*100)}%`;}
function arr(value:unknown){return Array.isArray(value)?value as Array<Record<string,unknown>>:[];}

export function AiQualityPanel({metrics}:{metrics:Record<string,unknown>}){
 const models=arr(metrics.models),categories=arr(metrics.categories);
 return <section className="co-section ai-quality-panel">
  <div className="co-section-heading"><div><p className="co-kicker">AI Quality 0.9.5</p><h2>Jakość, korekty i stabilność Brain</h2></div><strong>ostatnie {String(metrics.days??30)} dni</strong></div>
  <div className="co-metric-grid"><article className="co-metric-card"><BrainCircuit/><span>Analizy</span><strong>{String(metrics.analyses??0)}</strong><small>średnia pewność {percent(metrics.averageConfidence)}</small></article><article className="co-metric-card"><CheckCircle2/><span>Decyzje człowieka</span><strong>{String(metrics.reviews??0)}</strong><small>{String(metrics.approvals??0)} akceptacji · {String(metrics.rejections??0)} odrzuceń</small></article><article className="co-metric-card"><Gauge/><span>Wskaźnik korekt</span><strong>{percent(metrics.correctionRate)}</strong><small>mierzy rozbieżność AI ↔ człowiek</small></article><article className="co-metric-card"><TriangleAlert/><span>Błędy pipeline</span><strong>{String(metrics.errors??0)}</strong><small>{String(metrics.warnings??0)} ostrzeżeń analiz</small></article></div>
  <div className="control-dashboard-grid"><article className="module-panel"><div className="module-panel__heading"><Activity size={20}/><div><p className="eyebrow">Modele i prompty</p><h3>Wersje pracujące na danych</h3></div></div><div className="live-record-list">{models.map((row,index)=><div className="command-row" key={`${String(row.model)}:${String(row.prompt_version)}:${index}`}><div><strong>{String(row.model)}</strong><span>{String(row.prompt_version)} · {String(row.count)} analiz</span></div></div>)}{models.length===0?<p className="empty-copy">Metryki pojawią się po pierwszej analizie dokumentu.</p>:null}</div></article><article className="module-panel"><div className="module-panel__heading"><Gauge size={20}/><div><p className="eyebrow">Kategorie</p><h3>Jakość klasyfikacji</h3></div></div><div className="live-record-list">{categories.map((row,index)=><div className="command-row" key={`${String(row.category)}:${index}`}><div><strong>{String(row.category)}</strong><span>{String(row.count)} analiz · pewność {percent(row.avg_confidence)}</span></div></div>)}</div></article></div>
 </section>;
}
