import { describe, expect, it } from "vitest";
import { buildInvestmentAutopilotSnapshot, changeConsequences, type AutopilotInput } from "../lib/investments/autopilot";

function input(overrides: Partial<AutopilotInput> = {}): AutopilotInput {
  return { nowIso:"2026-08-17T12:00:00.000Z",projectId:"project-1",workspaceId:"workspace-1",documents:[{id:"d1",name:"Projekt wentylacji R02.pdf",ai_status:"ready",review_status:"approved"}],facts:[{id:"f1",source_reference_id:"ref-1",status:"approved"}],requirements:[],protocolRequirements:[],protocols:[],materialRequests:[],scheduleActivities:[],impacts:[],evidence:[],findings:[],materials:[{id:"m1",name:"Kanały wentylacyjne",installation:"Wentylacja",specification:"klasa B"}],devices:[{id:"u1",name:"Centrala AHU-1",installation:"Wentylacja",parameters:{}}],wbsNodes:[{id:"w1",code:"40",name:"Wentylacja",installation:"Wentylacja",status:"active"}],boqItems:[{id:"b1",item_number:"3.1",description:"Kanały wentylacyjne",quantity:100,quantity_executed:30,quantity_accepted:25,unit:"m2",unit_price:100,total_price:10000,wbs_node_id:"w1"}],boqVersions:[{id:"bv1",status:"approved",version_number:1}],aiDecisions:[],finance:null,warehouse:null,...overrides };
}

describe("Investment Autopilot",()=>{
  it("kieruje zadania możliwe do przygotowania przez AI do Autopilota",()=>{const snapshot=buildInvestmentAutopilotSnapshot(input({requirements:[{id:"r1",requirement_type:"material_application",title:"WM – kanały",description:"Zatwierdzić system",status:"proposed",confidence:.95,source_document_id:"d1"}],protocolRequirements:[{id:"pr1",protocol_type:"air_balance",title:"Pomiary i regulacja",status:"required",trigger_rule:{wbs:"40"},required_evidence:["raport"]}]}));expect(snapshot.aiCanDoCount).toBe(2);expect(snapshot.missions.some((mission)=>mission.actionLabel==="Przygotuj szkic WM")).toBe(true);expect(snapshot.missions.some((mission)=>mission.actionLabel==="Przygotuj szkic")).toBe(true);});
  it("nie traktuje rzeczywistego wyniku próby jako czynności automatycznej",()=>{const snapshot=buildInvestmentAutopilotSnapshot(input({protocolRequirements:[{id:"pr1",protocol_type:"pressure_test",title:"Próba ciśnieniowa",status:"required",trigger_rule:{wbs:"30"},required_evidence:["manometr"]}],protocols:[{id:"p1",protocol_type:"pressure_test",title:"Próba ciśnieniowa",status:"draft",payload:{result:null}}]}));const mission=snapshot.missions.find((row)=>row.id==="protocol:pr1");expect(mission?.owner).toBe("field");expect(mission?.description).toContain("rzeczywistej próby");});
  it("oznacza przeterminowaną ścieżkę krytyczną jako blokadę",()=>{const snapshot=buildInvestmentAutopilotSnapshot(input({scheduleActivities:[{id:"s1",code:"H-40",title:"Montaż wentylacji",status:"active",planned_start:"2026-07-01",planned_finish:"2026-08-10",actual_finish:null,critical:true,wbs_node_id:"w1"}]}));expect(snapshot.blockerCount).toBeGreaterThan(0);expect(snapshot.missions[0]?.priority).toBe("critical");expect(snapshot.healthScore).toBeLessThan(100);});
  it("Change Radar wylicza skutki dla protokołów i materiałów",()=>{const effects=changeConsequences("protocols","Zmiana materiału i próby szczelności wentylacji");expect(effects.some((item)=>item.includes("protoko"))).toBe(true);expect(effects.some((item)=>item.includes("wnioski materiałowe"))).toBe(true);expect(effects.some((item)=>item.includes("wentylacji"))).toBe(true);});
  it("wykrywa sprzedaż wyższą od wartości odebranego BOQ",()=>{const snapshot=buildInvestmentAutopilotSnapshot(input({finance:{allocations:[{id:"a1",source_type:"invoice",source_id:"i1",amount:5000,status:"approved"}],invoices:[{id:"i1",invoice_number:"FV-S/1",direction:"sale",net_amount:5000,status:"issued"}],invoiceLines:[{invoice_id:"i1",description:"Przerób",quantity:1,unit:"kpl",net_amount:5000}]}}));expect(snapshot.reconciliation.acceptedWorkValue).toBe(2500);expect(snapshot.reconciliation.findings.some((finding)=>finding.id==="sales-over-progress")).toBe(true);});
  it("buduje matrycę instalacji z BOQ, planu, WM, protokołów i dowodów",()=>{const snapshot=buildInvestmentAutopilotSnapshot(input({materialRequests:[{id:"mr1",title:"WM – wentylacja",status:"approved",payload:{installation:"Wentylacja"}}],scheduleActivities:[{id:"s1",code:"H40",title:"Montaż",status:"active",planned_start:"2026-08-01",planned_finish:"2026-09-01",actual_finish:null,critical:false,wbs_node_id:"w1"}],protocolRequirements:[{id:"pr1",protocol_type:"air_balance",title:"Regulacja wentylacji",status:"required",trigger_rule:{wbs:"40"},required_evidence:[]}],protocols:[{id:"p1",protocol_type:"air_balance",title:"Regulacja wentylacji",status:"closed",payload:{}}],evidence:[{id:"e1",evidence_type:"measurement",title:"Raport pomiarów",status:"accepted",due_at:null,wbs_node_id:"w1"}]}));const ventilation=snapshot.installations.find((row)=>row.name==="Wentylacja");expect(ventilation).toBeTruthy();expect(ventilation?.boqItems).toBe(1);expect(ventilation?.scheduleActivities).toBe(1);expect(ventilation?.protocolsClosed).toBe(1);expect(ventilation?.evidenceComplete).toBe(1);});
});
