import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const migration = readFileSync(
  "supabase/migrations/20260907130451_rls_authorization_and_index_hardening_480.sql",
  "utf8"
);

describe("RLS authorization hardening 480", () => {
  it("removes legacy project and task membership policies that bypass domain access", () => {
    expect(migration).toContain('drop policy if exists "project_tasks_project_member"');
    expect(migration).toContain('drop policy if exists "members can read projects"');
    expect(migration).toContain('drop policy if exists "users can read own memberships"');
    expect(migration).toContain('drop policy if exists "workspace members can read workspaces"');
  });

  it("splits Warehouse write policies so they do not also become permissive SELECT policies", () => {
    for (const table of [
      "stock_item_location_assignments",
      "warehouse_ai_decision_events",
      "warehouse_ai_feedback",
      "warehouse_locations"
    ]) {
      expect(migration).toContain(`drop policy if exists ${table}_write`);
      expect(migration).toContain(`create policy ${table}_insert`);
      expect(migration).toContain(`create policy ${table}_update`);
      expect(migration).toContain(`create policy ${table}_delete`);
    }
  });

  it("drops only duplicate autogenerated project task indexes", () => {
    expect(migration).toContain("drop index if exists public.project_tasks_fk_b44cfc1775_idx");
    expect(migration).toContain("drop index if exists public.project_tasks_fk_c9aa275ab1_idx");
    expect(migration).not.toContain("drop index if exists public.project_tasks_assigned_to_idx");
    expect(migration).not.toContain("drop index if exists public.project_tasks_created_by_idx");
  });
});
