"use client";

import { useMemo, useState, useTransition, type ComponentProps, type FormEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { BriefcaseBusiness, BrainCircuit, GraduationCap, PlugZap, Route, Sparkles, UsersRound } from "lucide-react";
import { HrWorkspaceCore300 } from "./hr-workspace-core-300";
import styles from "./hr-market-400.module.css";

type Props = ComponentProps<typeof HrWorkspaceCore300>;
type Row = Record<string, unknown>;
type Mode = "operations" | "talent" | "development" | "planning" | "mobility" | "integrations";
type Field = { name: string; label: string; type?: "text" | "number" | "date" | "datetime-local" | "textarea" | "select"; required?: boolean; options?: Array<[string,string]>; rows?: Row[]; rowLabel?: (row: Row)=>string; full?: boolean; placeholder?: string };

const text=(v:unknown,f="—")=>v===null||v===undefined||v===""?f:String(v);
const num=(v:unknown,d=1)=>new Intl.NumberFormat("pl-PL",{maximumFractionDigits:d}).format(Number(v??0)||0);
const money=(v:unknown)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:2}).format(Number(v??0)||0);
const date=(v:unknown)=>{if(!v)return"—";const x=new Date(String(v));return Number.isNaN(x.getTime())?String(v):new Intl.DateTimeFormat("pl-PL").format(x)};
const employeeLabel=(r:Row)=>`${text(r.first_name,"")} ${text(r.last_name,"")}`.trim()||text(r.employee_number);
const projectLabel=(r:Row)=>text(r.name);
const statusTone=(v:unknown)=>["ready","active","open","completed","done","approved","hired"].includes(String(v))?styles.good:["blocked","critical","rejected","overdue","error"].includes(String(v))?styles.bad:styles.warn;

function Kpi({label,value}:{label:string;value:ReactNode}){return <div className={styles.kpi}><small>{label}</small><strong>{value}</strong></div>}
function Panel({title,kicker,children,wide=false}:{title:string;kicker?:string;children:ReactNode;wide?:boolean}){return <section className={`${styles.panel} ${wide?styles.wide:""}`}><div className={styles.head}><div>{kicker?<small>{kicker}</small>:null}<h2>{title}</h2></div></div>{children}</section>}
function Badge({children,tone=styles.badge}:{children:ReactNode;tone?:string}){return <span className={tone}>{children}</span>}
function MiniForm({title,action,fields,disabled,pending,onSubmit}:{title:string;action:string;fields:Field[];disabled?:boolean;pending:boolean;onSubmit:(action:string,e:FormEvent<HTMLFormElement>)=>void}){
  return <details className={styles.form}><summary>{title}</summary><form onSubmit={e=>onSubmit(action,e)}><div className={styles.fields}>{fields.map(f=><label key={f.name} className={f.full?styles.full:undefined}><span>{f.label}</span>{f.type==="textarea"?<textarea name={f.name} required={f.required} placeholder={f.placeholder}/>:f.options||f.rows||f.type==="select"?<select name={f.name} required={f.required}><option value="">Wybierz</option>{f.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}{f.rows?.map(r=><option key={String(r.id)} value={String(r.id)}>{f.rowLabel?f.rowLabel(r):text(r.name??r.title??r.id)}</option>)}</select>:<input name={f.name} type={f.type??"text"} required={f.required} placeholder={f.placeholder} step={f.type==="number"?"any":undefined}/>}</label>)}</div><div className={styles.fields}><button className={styles.button} disabled={disabled||pending}>{pending?"Zapisywanie…":"Zapisz"}</button></div></form></details>
}

export function HrMarket400(props: Props){
  const router=useRouter();const [pending,startTransition]=useTransition();const [mode,setMode]=useState<Mode>("operations");const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [issuedSecret,setIssuedSecret]=useState<string|null>(null);
  const data=props.data as unknown as Record<string,unknown>;
  const employees=(data.employees??[]) as Row[],projects=(data.projects??[]) as Row[];
  const requisitions=(data.jobRequisitions??[]) as Row[],candidates=(data.candidates??[]) as Row[],candidateEvents=(data.candidateEvents??[]) as Row[],lifecycle=(data.lifecycleTasks??[]) as Row[];
  const trips=(data.businessTrips??[]) as Row[],tripExpenses=(data.businessTripExpenses??[]) as Row[],competencies=(data.competencyCatalog??[]) as Row[],employeeCompetencies=(data.employeeCompetencies??[]) as Row[],training=(data.trainingPlans??[]) as Row[];
  const cycles=(data.performanceCycles??[]) as Row[],goals=(data.goals??[]) as Row[],reviews=(data.performanceReviews??[]) as Row[],demands=(data.workforceDemands??[]) as Row[],readiness=(data.readinessSnapshots??[]) as Row[],crew=(data.crewSuggestions??[]) as Row[];
  const compensation=(data.compensationEvents??[]) as Row[],bonuses=(data.bonuses??[]) as Row[],surveys=(data.surveys??[]) as Row[],career=(data.careerPaths??[]) as Row[],succession=(data.successionCandidates??[]) as Row[],requests=(data.employeeRequests??[]) as Row[];
  const rcp=(data.rcpConnections??[]) as Row[],rcpMappings=(data.rcpMappings??[]) as Row[],rcpEvents=(data.rcpEvents??[]) as Row[],recommendations=(data.hrAiRecommendations??[]) as Row[],summary=(data.hr400Summary??{}) as Row;
  const employeeById=useMemo(()=>new Map(employees.map(r=>[String(r.id),r])),[employees]);const projectById=useMemo(()=>new Map(projects.map(r=>[String(r.id),r])),[projects]);
  const requisitionById=useMemo(()=>new Map(requisitions.map(r=>[String(r.id),r])),[requisitions]);
  const run=(action:string,payload:Record<string,unknown>)=>{setMessage(null);setError(null);setIssuedSecret(null);startTransition(async()=>{try{const res=await fetch("/api/company/hr-market",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId:props.workspaceId,action,payload})});const out=await res.json().catch(()=>({})) as {error?:string;issuedSecret?:string};if(!res.ok)throw new Error(out.error??"Operacja nie powiodła się.");if(out.issuedSecret)setIssuedSecret(out.issuedSecret);setMessage("Operacja została wykonana.");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Operacja nie powiodła się.")}})};
  const submit=(action:string,e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(action,Object.fromEntries(new FormData(e.currentTarget).entries()));};
  const modes:Array<[Mode,string,ReactNode]>=[["operations","Operacje",<BriefcaseBusiness size={14} key="a"/>],["talent","Talent i onboarding",<UsersRound size={14} key="b"/>],["development","Rozwój i wynagrodzenia",<GraduationCap size={14} key="c"/>],["planning","Planning AI",<BrainCircuit size={14} key="d"/>],["mobility","Delegacje i portal",<Route size={14} key="e"/>],["integrations","RCP i integracje",<PlugZap size={14} key="f"/>]];
  const latestReadiness=new Map<string,Row>();readiness.forEach(r=>{const id=String(r.employee_id);if(!latestReadiness.has(id))latestReadiness.set(id,r)});const blocked=[...latestReadiness.values()].filter(r=>String(r.status)==="blocked").length;
  return <div className={styles.shell} data-hr-market="4.0">
    <nav className={styles.modes} aria-label="Kadry 4.0">{modes.map(([id,label,icon])=><button type="button" key={id} className={`${styles.mode} ${mode===id?styles.active:""}`} onClick={()=>setMode(id)}>{icon} {label}</button>)}</nav>
    {mode!=="operations"?<div className={styles.kpis}><Kpi label="Aktywni" value={text(summary.activeEmployees,"0")}/><Kpi label="People Readiness — blokady" value={text(summary.blockedPeople,String(blocked))}/><Kpi label="Otwarte rekrutacje" value={text(summary.openJobs,String(requisitions.filter(r=>r.status==="open").length))}/><Kpi label="Szkolenia" value={text(summary.plannedTrainings,String(training.length))}/><Kpi label="Braki obsady" value={text(summary.openDemands,String(demands.length))}/><Kpi label="AI Controller" value={text(summary.aiRecommendations,String(recommendations.filter(r=>r.status==="new").length))}/></div>:null}
    {message?<div className={`${styles.feedback} ${styles.success}`}>{message}</div>:null}{error?<div className={`${styles.feedback} ${styles.error}`}>{error}</div>:null}
    {issuedSecret?<div className={styles.guard}><strong>Sekret webhooka RCP — pokażemy go tylko teraz.</strong><div className={styles.secret}>{issuedSecret}</div><div>Endpoint: <code>/api/integrations/hr/rcp?connectionId=ID_INTEGRACJI</code></div></div>:null}
    {mode==="operations"?<HrWorkspaceCore300 {...props}/>:null}

    {mode==="talent"?<div className={styles.grid}>
      <Panel title="Rekrutacja / ATS" kicker="Wakat → kandydat → rozmowa → decyzja">
        {props.canWrite?<MiniForm title="Nowe zapotrzebowanie rekrutacyjne" action="requisition_create" pending={pending} onSubmit={submit} fields={[{name:"title",label:"Nazwa rekrutacji",required:true},{name:"position",label:"Stanowisko",required:true},{name:"department",label:"Dział"},{name:"headcount",label:"Liczba osób",type:"number"},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"employmentType",label:"Forma zatrudnienia"},{name:"location",label:"Lokalizacja"},{name:"requiredQualifications",label:"Wymagane uprawnienia",placeholder:"np. UDT, SEP"},{name:"minCompensation",label:"Widełki od",type:"number"},{name:"maxCompensation",label:"Widełki do",type:"number"},{name:"targetStart",label:"Start",type:"date"},{name:"description",label:"Opis",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{requisitions.slice(0,12).map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.title)} · {text(r.position)}</h3><p>{text(r.headcount)} os. · {r.project_id?projectLabel(projectById.get(String(r.project_id))??{}):"bez inwestycji"} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p>{props.canApprove&&r.status==="draft"?<div className={styles.actions}><button className={styles.secondary} onClick={()=>run("requisition_approve",{requisitionId:r.id})}>Otwórz rekrutację</button></div>:null}</div>)}</div>
      </Panel>
      <Panel title="Kandydaci" kicker="Bez algorytmicznego rankingu ludzi">
        <div className={styles.guard}>Octopus nie ocenia automatycznie „wartości” kandydata i nie podejmuje decyzji zatrudnij/odrzuć. AI może porządkować dokumenty, ale decyzja rekrutacyjna pozostaje ludzka.</div>
        {props.canWrite?<MiniForm title="Dodaj kandydata" action="candidate_create" pending={pending} onSubmit={submit} fields={[{name:"requisitionId",label:"Rekrutacja",rows:requisitions,rowLabel:r=>`${text(r.title)} · ${text(r.position)}`},{name:"firstName",label:"Imię",required:true},{name:"lastName",label:"Nazwisko",required:true},{name:"email",label:"E-mail"},{name:"phone",label:"Telefon"},{name:"source",label:"Źródło"},{name:"consentUntil",label:"Zgoda do",type:"date"},{name:"notes",label:"Notatki",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{candidates.slice(0,16).map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.first_name)} {text(r.last_name)}</h3><p>{r.requisition_id?text(requisitionById.get(String(r.requisition_id))?.position):"bez przypisania"} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p>{props.canApprove?<div className={styles.actions}>{["screening","interview","offer","hired","rejected"].map(st=><button key={st} className={styles.secondary} onClick={()=>run("candidate_status",{candidateId:r.id,status:st})}>{st}</button>)}</div>:null}</div>)}</div>
      </Panel>
      <Panel title="Onboarding / Offboarding" kicker="Checklisty, dokumenty, sprzęt i odpowiedzialność" wide>
        {props.canWrite?<MiniForm title="Dodaj zadanie lifecycle" action="lifecycle_task_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"lifecycle",label:"Proces",type:"select",options:[["onboarding","Onboarding"],["offboarding","Offboarding"]],required:true},{name:"taskType",label:"Typ",placeholder:"sprzęt / BHP / badania / dokument / dostęp"},{name:"title",label:"Zadanie",required:true},{name:"dueDate",label:"Termin",type:"date"},{name:"responsibleEmployeeId",label:"Odpowiedzialny",rows:employees,rowLabel:employeeLabel},{name:"description",label:"Opis",type:"textarea",full:true}]}/>:null}
        <div className={styles.table}><table><thead><tr><th>Pracownik</th><th>Proces</th><th>Zadanie</th><th>Termin</th><th>Status</th><th>Akcja</th></tr></thead><tbody>{lifecycle.slice(0,30).map(r=><tr key={String(r.id)}><td>{employeeLabel(employeeById.get(String(r.employee_id))??{})}</td><td>{text(r.lifecycle)}</td><td>{text(r.title)}</td><td>{date(r.due_date)}</td><td><Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></td><td>{props.canWrite&&r.status!=="done"?<button className={styles.secondary} onClick={()=>run("lifecycle_task_status",{taskId:r.id,status:"done"})}>Zakończ</button>:"—"}</td></tr>)}</tbody></table></div>
      </Panel>
    </div>:null}

    {mode==="development"?<div className={styles.grid}>
      <Panel title="Kompetencje i szkolenia" kicker="Matryca umiejętności + plan rozwoju">
        {props.canWrite?<><MiniForm title="Nowa kompetencja" action="competency_create" pending={pending} onSubmit={submit} fields={[{name:"code",label:"Kod",required:true},{name:"name",label:"Nazwa",required:true},{name:"category",label:"Kategoria"},{name:"levelScale",label:"Skala",type:"number"},{name:"description",label:"Opis",type:"textarea",full:true}]}/><MiniForm title="Przypisz kompetencję" action="competency_assign" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"competencyId",label:"Kompetencja",rows:competencies,rowLabel:r=>text(r.name),required:true},{name:"level",label:"Poziom",type:"number",required:true},{name:"verified",label:"Zweryfikowana",type:"select",options:[["true","Tak"],["false","Nie"]]},{name:"validUntil",label:"Ważna do",type:"date"}]}/><MiniForm title="Zaplanuj szkolenie" action="training_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel},{name:"competencyId",label:"Kompetencja",rows:competencies,rowLabel:r=>text(r.name)},{name:"title",label:"Szkolenie",required:true},{name:"provider",label:"Organizator"},{name:"plannedDate",label:"Planowana data",type:"date"},{name:"dueDate",label:"Termin",type:"date"},{name:"cost",label:"Koszt",type:"number"}]}/></>:null}
        <div className={styles.line}><span>Kompetencje w katalogu</span><strong>{competencies.length}</strong></div><div className={styles.line}><span>Przypisane kompetencje</span><strong>{employeeCompetencies.length}</strong></div><div className={styles.line}><span>Szkolenia w planie</span><strong>{training.filter(r=>!["completed","cancelled"].includes(String(r.status))).length}</strong></div>
      </Panel>
      <Panel title="Oceny, cele i OKR" kicker="Human-in-the-loop">
        {props.canWrite?<><MiniForm title="Nowy cykl ocen" action="performance_cycle_create" pending={pending} onSubmit={submit} fields={[{name:"name",label:"Nazwa",required:true},{name:"dateFrom",label:"Od",type:"date",required:true},{name:"dateTo",label:"Do",type:"date",required:true},{name:"methodology",label:"Metoda",type:"select",options:[["goals","Cele / OKR"],["90","90°"],["180","180°"]]}]}/><MiniForm title="Dodaj cel" action="goal_create" pending={pending} onSubmit={submit} fields={[{name:"cycleId",label:"Cykl",rows:cycles,rowLabel:r=>text(r.name)},{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"title",label:"Cel",required:true},{name:"targetValue",label:"Wartość docelowa",type:"number"},{name:"unit",label:"Jednostka"},{name:"weight",label:"Waga",type:"number"},{name:"dueDate",label:"Termin",type:"date"}]}/></>:null}
        <div className={styles.cards}>{goals.slice(0,12).map(g=><div className={styles.card} key={String(g.id)}><h3>{employeeLabel(employeeById.get(String(g.employee_id))??{})} · {text(g.title)}</h3><p>{text(g.current_value,"0")} / {text(g.target_value)} {text(g.unit,"")} · {date(g.due_date)}</p></div>)}</div>
      </Panel>
      <Panel title="Wynagrodzenia, historia i premie" kicker="Kontrola kosztu pracodawcy">
        {!props.canViewPayroll?<div className={styles.guard}>Dane płacowe są ukryte zgodnie z uprawnieniami.</div>:<><div className={styles.line}><span>Historia zmian</span><strong>{compensation.length}</strong></div><div className={styles.line}><span>Premie</span><strong>{bonuses.length}</strong></div>{props.canManagePayroll?<><MiniForm title="Zapisz zmianę wynagrodzenia" action="compensation_event_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"eventType",label:"Typ",type:"select",options:[["review","Przegląd"],["raise","Podwyżka"],["promotion","Awans"],["role_change","Zmiana roli"],["correction","Korekta"]]},{name:"effectiveFrom",label:"Od",type:"date"},{name:"oldGross",label:"Poprzednie brutto",type:"number"},{name:"newGross",label:"Nowe brutto",type:"number"},{name:"oldEmployerCost",label:"Poprzedni koszt pracodawcy",type:"number"},{name:"newEmployerCost",label:"Nowy koszt pracodawcy",type:"number"},{name:"reason",label:"Powód",type:"textarea",full:true}]}/><MiniForm title="Dodaj premię" action="bonus_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"periodMonth",label:"Miesiąc",type:"date",required:true},{name:"bonusType",label:"Rodzaj",required:true},{name:"amount",label:"Kwota",type:"number",required:true},{name:"reason",label:"Powód",type:"textarea",full:true}]}/></>:null}</>}
      </Panel>
      <Panel title="Ankiety, kariera i sukcesja" kicker="Engagement + rozwój" wide>
        <div className={styles.three}>{props.canWrite?<><MiniForm title="Nowa ankieta" action="survey_create" pending={pending} onSubmit={submit} fields={[{name:"title",label:"Nazwa",required:true},{name:"description",label:"Opis"},{name:"anonymous",label:"Anonimowa",type:"select",options:[["true","Tak"],["false","Nie"]]},{name:"dateFrom",label:"Od",type:"date"},{name:"dateTo",label:"Do",type:"date"},{name:"questions",label:"Pytania",type:"textarea",full:true,placeholder:"Jedno pytanie na linię"}]}/><MiniForm title="Ścieżka kariery" action="career_path_create" pending={pending} onSubmit={submit} fields={[{name:"name",label:"Nazwa",required:true},{name:"currentRole",label:"Rola startowa"},{name:"targetRole",label:"Rola docelowa"}]}/></>:null}<div className={styles.card}><h3>Stan</h3><p>Ankiety: {surveys.length}<br/>Ścieżki kariery: {career.length}<br/>Plany sukcesji: {succession.length}<br/>Decyzje sukcesyjne pozostają ręczne.</p></div></div>
      </Panel>
    </div>:null}

    {mode==="planning"?<div className={styles.grid}>
      <Panel title="People Readiness" kicker="Czy pracownik może dziś bezpiecznie pracować?">
        <div className={styles.cards}>{[...latestReadiness.values()].sort((a,b)=>Number(a.score)-Number(b.score)).slice(0,16).map(r=><div className={styles.card} key={String(r.id)}><h3>{employeeLabel(employeeById.get(String(r.employee_id))??{})} <Badge tone={statusTone(r.status)}>{text(r.status)} · {num(r.score,0)}/100</Badge></h3><div className={styles.bar}><span style={{width:`${Math.max(0,Math.min(100,Number(r.score)||0))}%`}}/></div><p>{Array.isArray(r.blockers)?(r.blockers as string[]).join(" "):"Brak krytycznych blokad."}</p></div>)}</div>
      </Panel>
      <Panel title="AI HR Controller" kicker="Alerty operacyjne, nie decyzje kadrowe">
        {props.canWrite?<div className={styles.actions}><button className={styles.button} disabled={pending} onClick={()=>run("refresh_intelligence",{referenceDate:data.referenceDate})}><Sparkles size={13}/> Przelicz analizę</button></div>:null}
        <div className={styles.cards}>{recommendations.filter(r=>r.status==="new").slice(0,15).map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.title)} <Badge tone={statusTone(r.severity)}>{text(r.severity)}</Badge></h3><p>{text(r.description)}</p>{props.canApprove?<div className={styles.actions}><button className={styles.secondary} onClick={()=>run("recommendation_status",{recommendationId:r.id,status:"accepted"})}>Przyjmij</button><button className={styles.danger} onClick={()=>run("recommendation_status",{recommendationId:r.id,status:"dismissed"})}>Pomiń</button></div>:null}</div>)}</div>
      </Panel>
      <Panel title="Zapotrzebowanie na ludzi" kicker="Inwestycja → rola → termin → kompetencje">
        {props.canWrite?<MiniForm title="Dodaj zapotrzebowanie i policz obsadę" action="demand_create" pending={pending} onSubmit={submit} fields={[{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel,required:true},{name:"dateFrom",label:"Od",type:"date",required:true},{name:"dateTo",label:"Do",type:"date",required:true},{name:"role",label:"Rola",required:true},{name:"requiredCount",label:"Liczba osób",type:"number",required:true},{name:"requiredQualifications",label:"Uprawnienia",placeholder:"np. UDT, SEP"},{name:"shift",label:"Zmiana"},{name:"notes",label:"Uwagi",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{demands.slice(0,12).map(r=><div className={styles.card} key={String(r.id)}><h3>{projectLabel(projectById.get(String(r.project_id))??{})} · {text(r.role)} · {text(r.required_count)} os.</h3><p>{date(r.date_from)}–{date(r.date_to)} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p>{props.canWrite?<button className={styles.secondary} onClick={()=>run("crew_build",{demandId:r.id})}>AI Crew Builder</button>:null}</div>)}</div>
      </Panel>
      <Panel title="AI Crew Builder" kicker="Gotowość + kwalifikacje + kompetencje + dostępność + koszt">
        <div className={styles.guard}>Scoring dotyczy wyłącznie dopasowania operacyjnego do konkretnego zadania. Nie wykorzystuje cech chronionych i nie jest automatyczną decyzją o zatrudnieniu, awansie ani zwolnieniu.</div>
        <div className={styles.table}><table><thead><tr><th>Pracownik</th><th>Gotowość</th><th>Uprawnienia</th><th>Kompetencje</th><th>Dostępność</th><th>Wynik</th></tr></thead><tbody>{crew.slice(0,25).map(r=><tr key={String(r.id)}><td>{r.recommended?<Badge tone={styles.good}>Rekomendowany</Badge>:null} {employeeLabel(employeeById.get(String(r.employee_id))??{})}</td><td>{num(r.readiness_score,0)}</td><td>{num(r.qualification_score,0)}</td><td>{num(r.competency_score,0)}</td><td>{num(r.availability_score,0)}</td><td><strong>{num(r.overall_score,0)}</strong></td></tr>)}</tbody></table></div>
      </Panel>
    </div>:null}

    {mode==="mobility"?<div className={styles.grid}>
      <Panel title="Delegacje i rozliczenia" kicker="Kilometrówka, dieta, hotel, zaliczka">
        {props.canWrite?<MiniForm title="Nowa delegacja" action="trip_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"projectId",label:"Inwestycja",rows:projects,rowLabel:projectLabel},{name:"destination",label:"Miejsce",required:true},{name:"purpose",label:"Cel",required:true},{name:"dateFrom",label:"Od",type:"date",required:true},{name:"dateTo",label:"Do",type:"date",required:true},{name:"transportMode",label:"Transport"},{name:"distanceKm",label:"Kilometry",type:"number"},{name:"mileageRate",label:"Stawka/km",type:"number"},{name:"perDiem",label:"Dieta",type:"number"},{name:"advanceAmount",label:"Zaliczka",type:"number"},{name:"notes",label:"Uwagi",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{trips.slice(0,15).map(r=><div className={styles.card} key={String(r.id)}><h3>{employeeLabel(employeeById.get(String(r.employee_id))??{})} → {text(r.destination)}</h3><p>{date(r.date_from)}–{date(r.date_to)} · dieta {money(r.per_diem)} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p>{props.canApprove&&r.status==="draft"?<button className={styles.secondary} onClick={()=>run("trip_status",{tripId:r.id,status:"approved"})}>Zatwierdź</button>:null}</div>)}</div>
      </Panel>
      <Panel title="Portal pracownika / wnioski" kicker="Self-service">
        {props.canWrite?<MiniForm title="Nowy wniosek pracownika" action="employee_request_create" pending={pending} onSubmit={submit} fields={[{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"requestType",label:"Typ",type:"select",options:[["data_change","Zmiana danych"],["certificate","Zaświadczenie"],["equipment","Sprzęt"],["schedule","Grafik"],["other","Inny"]],required:true},{name:"title",label:"Tytuł",required:true},{name:"details",label:"Szczegóły",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{requests.slice(0,15).map(r=><div className={styles.card} key={String(r.id)}><h3>{employeeLabel(employeeById.get(String(r.employee_id))??{})} · {text(r.title)}</h3><p>{text(r.request_type)} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge></p>{props.canApprove&&r.status==="submitted"?<div className={styles.actions}><button className={styles.secondary} onClick={()=>run("employee_request_status",{requestId:r.id,status:"approved"})}>Zatwierdź</button><button className={styles.danger} onClick={()=>run("employee_request_status",{requestId:r.id,status:"rejected"})}>Odrzuć</button></div>:null}</div>)}</div>
      </Panel>
      <Panel title="Koszty delegacji" kicker="Dokumenty i wydatki" wide><div className={styles.line}><span>Liczba wydatków</span><strong>{tripExpenses.length}</strong></div><div className={styles.line}><span>Łączna wartość</span><strong>{money(tripExpenses.reduce((sum,r)=>sum+Number(r.amount??0),0))}</strong></div></Panel>
    </div>:null}

    {mode==="integrations"?<div className={styles.grid}>
      <Panel title="RCP / rejestracja obecności" kicker="Provider-agnostic API">
        {props.canWrite?<MiniForm title="Nowe połączenie RCP" action="rcp_connection_create" pending={pending} onSubmit={submit} fields={[{name:"provider",label:"Dostawca",placeholder:"np. Roger, Hikvision, Generic API"},{name:"name",label:"Nazwa integracji",required:true},{name:"mode",label:"Tryb",type:"select",options:[["webhook","Webhook"],["poll","API polling"],["file","Plik/CSV"]]},{name:"capabilities",label:"Możliwości",placeholder:"in,out,break,presence"},{name:"notes",label:"Uwagi",type:"textarea",full:true}]}/>:null}
        <div className={styles.cards}>{rcp.map(r=><div className={styles.card} key={String(r.id)}><h3>{text(r.name)} · {text(r.provider)}</h3><p>{text(r.mode)} · <Badge tone={statusTone(r.status)}>{text(r.status)}</Badge> · ostatnia synchronizacja {date(r.last_sync_at)}</p><div className={styles.secret}>connectionId={text(r.id)}</div></div>)}</div>
      </Panel>
      <Panel title="Mapowanie pracowników RCP" kicker="Zewnętrzny ID → pracownik Octopus">
        {props.canWrite?<MiniForm title="Dodaj mapowanie" action="rcp_map" pending={pending} onSubmit={submit} fields={[{name:"connectionId",label:"Integracja",rows:rcp,rowLabel:r=>text(r.name),required:true},{name:"employeeId",label:"Pracownik",rows:employees,rowLabel:employeeLabel,required:true},{name:"externalEmployeeId",label:"ID w systemie RCP",required:true}]}/>:null}
        <div className={styles.line}><span>Mapowania</span><strong>{rcpMappings.length}</strong></div><div className={styles.line}><span>Zdarzenia RCP</span><strong>{rcpEvents.length}</strong></div><div className={styles.line}><span>Nieprzetworzone</span><strong>{rcpEvents.filter(r=>r.processed===false).length}</strong></div>
        <div className={styles.guard}>RCP nie zatwierdza samodzielnie czasu pracy. Zdarzenia wejść/wyjść są źródłem do uzgodnienia z timesheetami i wymagają istniejących reguł akceptacji.</div>
      </Panel>
    </div>:null}
  </div>
}
