-- Octopus Multi-AI Core 1.0
-- Per-model audit and consensus layer. Models only recommend; financial truth still changes through protected review actions.

create table if not exists public.ai_model_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  review_id uuid not null references public.finance_document_reviews(id) on delete cascade,
  insight_id uuid references public.finance_document_ai_insights(id) on delete cascade,
  recommended_project_id uuid references public.projects(id) on delete set null,
  provider text not null check (provider in ('gemini-fast','gemini-deep','groq','cloudflare')),
  model text not null,
  role text not null check (role in ('primary','second_opinion','tie_breaker')),
  status text not null default 'success' check (status in ('success','failed','skipped')),
  recommendation text check (recommendation in ('duplicate_same','duplicate_distinct','assign_project','manual_review','dismiss')),
  confidence numeric(5,4) check (confidence between 0 and 1),
  risk_score numeric(5,4) check (risk_score between 0 and 1),
  response_ms integer not null default 0 check (response_ms >= 0),
  prompt_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_consensus_events (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  review_id uuid not null references public.finance_document_reviews(id) on delete cascade,
  insight_id uuid references public.finance_document_ai_insights(id) on delete cascade,
  recommended_project_id uuid references public.projects(id) on delete set null,
  winning_recommendation text not null check (winning_recommendation in ('duplicate_same','duplicate_distinct','assign_project','manual_review','dismiss')),
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  risk_score numeric(5,4) not null check (risk_score between 0 and 1),
  agreement_ratio numeric(5,4) not null check (agreement_ratio between 0 and 1),
  requires_human boolean not null default false,
  providers jsonb not null default '[]'::jsonb,
  summary text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_model_runs_workspace_id on public.ai_model_runs(workspace_id);
create index if not exists idx_ai_model_runs_review_id on public.ai_model_runs(review_id);
create index if not exists idx_ai_model_runs_insight_id on public.ai_model_runs(insight_id);
create index if not exists idx_ai_model_runs_project_id on public.ai_model_runs(recommended_project_id);
create index if not exists idx_ai_model_runs_review_created on public.ai_model_runs(review_id,created_at desc);
create index if not exists idx_ai_consensus_events_workspace_id on public.ai_consensus_events(workspace_id);
create index if not exists idx_ai_consensus_events_review_id on public.ai_consensus_events(review_id);
create index if not exists idx_ai_consensus_events_insight_id on public.ai_consensus_events(insight_id);
create index if not exists idx_ai_consensus_events_project_id on public.ai_consensus_events(recommended_project_id);
create index if not exists idx_ai_consensus_events_review_created on public.ai_consensus_events(review_id,created_at desc);

alter table public.ai_model_runs enable row level security;
alter table public.ai_consensus_events enable row level security;

drop policy if exists "finance members read ai model runs" on public.ai_model_runs;
create policy "finance members read ai model runs" on public.ai_model_runs
for select using (private.has_domain_access(workspace_id,'finance','read',recommended_project_id));

drop policy if exists "finance members read ai consensus" on public.ai_consensus_events;
create policy "finance members read ai consensus" on public.ai_consensus_events
for select using (private.has_domain_access(workspace_id,'finance','read',recommended_project_id));

comment on table public.ai_model_runs is 'Auditable provider/model votes generated by Octopus Multi-AI Core. No row changes financial truth directly.';
comment on table public.ai_consensus_events is 'Consensus decisions produced from one or more AI model votes, with disagreement forcing human review.';
