"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Archive, CheckCircle2, CircleDashed, Download, FileJson2, LoaderCircle, PackageCheck, RefreshCw, ShieldCheck, TriangleAlert, UsersRound } from "lucide-react";

type Requirement = { id:string; category:string; title:string; status:string; document_id:string|null; required:boolean };
type DocumentOption = { id:string; name:string };
type Output = { id:string; title:string; version_number:number; status:string; generated_at:string; warnings:unknown };
type Readiness={projectStatus?:string;ready?:boolean;blockers?:number;openTasks?:number;pendingDocuments?:number;pendingMaterialRequests?:number;pendingPurchaseOrders?:number;pendingFinance?:number;draftStockMovements?:number;activeAssignments?:number;activeTeams?:number;autoCloseAssignments?:number;autoCloseTeams?:number};
type Props={projectId:string;projectStatus:string;canManage:boolean;readiness:Readiness;requirements:Requirement[];documents:DocumentOption[];outputs:Output[]};

const n=(value:unknown)=>Number(value??0);

export function CloseoutWorkspace({projectId,projectStatus,canManage,readiness,requirements,documents,outputs}:Props){
 const router=useRouter();const[pending,startTransition]=useTransition();const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const readOnly=projectStatus==="completed"||projectStatus==="archived";const archived=projectStatus==="archived";const completed=projectStatus==="completed";const canMutate=canManage&&!readOnly;
 async function post(body:Record<string,unknown>){const response=await fetch("/api/projects/closeout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,...body})});const result=await response.json() as {error?:string;id?:string;status?:string;version?:number};if(!response.ok)throw new Error(result.error??"Operacja pakietu przekazania nie powiodła się.");return result;}
 function setRequirement(item:Requirement,complete:boolean){if(!canMutate)return;let documentId=item.document_id??"";if(complete&&!documentId&&documents.length){documentId=window.prompt("Opcjonalnie wklej ID dokumentu dowodowego lub pozostaw puste.","")??"";}setError(null);setMessage(null);startTransition(async()=>{try{await post({action:"set_requirement",requirementId:item.id,complete,documentId:documentId||null});setMessage(complete?"Pozycja oznaczona jako kompletna.":"Pozycja ponownie otwarta.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function generate(){if(!canMutate)return;setError(null);setMessage(null);startTransition(async()=>{try{const r=await post({action:"generate"});setMessage(`Utworzono paczkę v${r.version} (${r.status}).`);router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 const recommended=requirements.filter(r=>r.required).length;const readyRecommended=requirements.filter(r=>r.required&&r.status==="complete").length;const percent=recommended?Math.round(readyRecommended/recommended*100):0;
 const openProcesses=n(readiness.openTasks)+n(readiness.pendingDocuments)+n(readiness.pendingMaterialRequests)+n(readiness.pendingPurchaseOrders)+n(readiness.pendingFinance)+n(readiness.draftStockMovements);
 const statusLabel=archived?"Archiwum":completed?"Zakończona":projectStatus==="active"?"Aktywna":projectStatus==="preparation"?"Przygotowanie":projectStatus==="paused"?"Wstrzymana":projectStatus;
 const checks=[
  ["Otwarte zadania",n(readiness.openTasks)],["Dokumenty do decyzji",n(readiness.pendingDocuments)],["Wnioski materiałowe",n(readiness.pendingMaterialRequests)],
  ["Zamówienia zakupowe",n(readiness.pendingPurchaseOrders)],["Finanse do rozliczenia",n(readiness.pendingFinance)],["Ruchy magazynowe w szkicu",n(readiness.draftStockMovements)]
 ] as const;
 return <div data-project-lifecycle-closeout="550">
 <p className="project-operation-card__success"><CheckCircle2 size={16}/><strong>Status inwestycji nie zależy od checklisty ani otwartych procesów.</strong> Zmień go bezpośrednio, klikając znacznik statusu przy nazwie inwestycji. Checklista i paczki poniżej są wyłącznie opcjonalnym narzędziem przekazania i archiwizacji dokumentów.</p>

 <section className="pw-submodule-metrics"><article data-tone="positive"><span>Kompletność pakietu</span><strong>{percent}%</strong><small>{readyRecommended}/{recommended} pozycji zalecanych</small></article><article data-tone={openProcesses?"warning":"positive"}><span>Otwarte procesy</span><strong>{openProcesses}</strong><small>informacyjnie — nie blokują statusu</small></article><article><span>Aktywne przypisania</span><strong>{n(readiness.activeAssignments)+n(readiness.activeTeams)}</strong><small>domykane automatycznie po zakończeniu</small></article><article><span>Status inwestycji</span><strong>{statusLabel}</strong><small>{archived?"można przywrócić":completed?"poza bieżącą pracą":"zmieniany z nagłówka"}</small></article></section>

 {message?<p className="project-operation-card__success"><CheckCircle2 size={16}/>{message}</p>:null}{error?<p className="project-operation-card__error"><TriangleAlert size={16}/>{error}</p>:null}
 {archived?<p className="project-operation-card__success"><Archive size={16}/><strong>Inwestycja jest w Archiwum.</strong> Pełna historia pozostaje zachowana. Użyj znacznika statusu przy nazwie inwestycji, aby przywrócić ją do Zakończonych lub ponownie aktywować.</p>:completed?<p className="project-operation-card__success"><CheckCircle2 size={16}/><strong>Inwestycja zakończona.</strong> Nie pojawia się w nowych wyborach operacyjnych, w tym w kalendarzu pracy pracowników. Status możesz zmienić z nagłówka.</p>:null}

 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Podgląd operacyjny</p><h2>Otwarte elementy — informacyjnie</h2><span>Te wartości nie blokują zmiany statusu inwestycji.</span></div><span className="status-chip">bez blokady</span></div><div className="closeout-list">{checks.map(([label,value])=><article key={label}>{value===0?<CheckCircle2 size={18}/>:<CircleDashed size={18}/>}<div><strong>{label}</strong><span>{value===0?"Brak otwartych pozycji":`${value} otwartych pozycji`}</span></div><span className={`status-chip ${value===0?"status-chip--positive":"status-chip--warning"}`}>{value}</span></article>)}<article><UsersRound size={18}/><div><strong>Aktywne przypisania pracowników / brygad</strong><span>{n(readiness.activeAssignments)+n(readiness.activeTeams)} — przy zmianie statusu na Zakończona lub Archiwum system domknie bieżące przypisania automatycznie.</span></div><span className="status-chip">auto</span></article></div></section>

 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Opcjonalna checklista</p><h2>Zakres przekazania</h2><span>Pomaga uporządkować dokumentację, ale nie jest warunkiem zakończenia inwestycji.</span></div>{canMutate?<button className="primary-button" disabled={pending||!requirements.length} onClick={generate}>{pending?<LoaderCircle className="spin" size={16}/>:<PackageCheck size={16}/>}Generuj wersję paczki</button>:<ShieldCheck size={22}/>}</div><div className="closeout-list">{requirements.map(item=><article key={item.id}>{item.status==="complete"?<CheckCircle2 size={18}/>:<CircleDashed size={18}/>}<div><small>{item.category}{item.required?" · zalecane":" · opcjonalne"}</small><strong>{item.title}</strong>{item.document_id?<span>Dowód: {documents.find(d=>d.id===item.document_id)?.name??item.document_id}</span>:null}</div><span className={`status-chip ${item.status==="complete"?"status-chip--positive":"status-chip--warning"}`}>{item.status==="complete"?"Kompletne":"Brak"}</span>{canMutate?<button className="secondary-button" disabled={pending} onClick={()=>setRequirement(item,item.status!=="complete")}>{item.status==="complete"?<><RefreshCw size={14}/>Otwórz ponownie</>:<><CheckCircle2 size={14}/>Potwierdź</>}</button>:null}</article>)}{!requirements.length?<div className="empty-state"><ShieldCheck size={25}/><strong>Brak checklisty przekazania</strong><span>{canMutate?"Możesz ją utworzyć, jeśli chcesz przygotować formalny pakiet dokumentów. Nie wpływa to na status inwestycji.":"Brak zapisanej checklisty."}</span></div>:null}</div></section>

 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Paczki przekazania</p><h2>Wersjonowane archiwa dokumentów</h2></div></div><div className="project-live-records">{outputs.map(output=><article className="project-live-record" key={output.id}><div><strong>{output.title} · v{output.version_number}</strong><p>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(output.generated_at))}</p><small>Status paczki: {output.status}</small></div><div><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=pdf`}><Download size={14}/>PDF</Link><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=json`}><FileJson2 size={14}/>Manifest JSON</Link></div></article>)}{!outputs.length?<p className="empty-copy">Nie wygenerowano jeszcze żadnej paczki przekazania.</p>:null}</div></section>
 </div>;
}
