"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Archive, CheckCircle2, CircleDashed, Download, FileJson2, LoaderCircle, PackageCheck, RefreshCw, ShieldCheck, TriangleAlert, UsersRound } from "lucide-react";

type Requirement = { id:string; category:string; title:string; status:string; document_id:string|null; required:boolean };
type DocumentOption = { id:string; name:string };
type Output = { id:string; title:string; version_number:number; status:string; generated_at:string; warnings:unknown };
type Readiness={projectStatus?:string;ready?:boolean;blockers?:number;openTasks?:number;pendingDocuments?:number;pendingMaterialRequests?:number;pendingPurchaseOrders?:number;pendingFinance?:number;draftStockMovements?:number;activeAssignments?:number;activeTeams?:number;autoCloseAssignments?:number;autoCloseTeams?:number};
type Props={projectId:string;projectStatus:string;canManage:boolean;readiness:Readiness;requirements:Requirement[];documents:DocumentOption[];outputs:Output[]};

const n=(value:unknown)=>Number(value??0);

export function CloseoutWorkspace({projectId,projectStatus,canManage,readiness,requirements,documents,outputs}:Props){
 const router=useRouter();const[pending,startTransition]=useTransition();const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const readOnly=projectStatus==="completed"||projectStatus==="archived";const archived=projectStatus==="archived";const completed=projectStatus==="completed";const canMutate=canManage&&!readOnly;
 async function post(body:Record<string,unknown>){const response=await fetch("/api/projects/closeout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,...body})});const result=await response.json() as {error?:string;id?:string;status?:string;version?:number};if(!response.ok)throw new Error(result.error??"Operacja closeout nie powiodła się.");return result;}
 function setRequirement(item:Requirement,complete:boolean){if(!canMutate)return;let documentId=item.document_id??"";if(complete&&!documentId&&documents.length){documentId=window.prompt("Opcjonalnie wklej ID dokumentu dowodowego lub pozostaw puste dla pozycji, które nie wymagają pliku.","")??"";}setError(null);setMessage(null);startTransition(async()=>{try{await post({action:"set_requirement",requirementId:item.id,complete,documentId:documentId||null});setMessage(complete?"Pozycja oznaczona jako kompletna.":"Pozycja ponownie otwarta.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function generate(){if(!canMutate)return;setError(null);setMessage(null);startTransition(async()=>{try{const r=await post({action:"generate"});setMessage(`Utworzono paczkę v${r.version} (${r.status}).`);router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function approve(outputId:string){if(!canMutate)return;setError(null);setMessage(null);if(!window.confirm("Zakończyć inwestycję? Po tej operacji bieżące przypisania pracowników zostaną domknięte, a nowe operacyjne wpisy dla tej inwestycji zostaną zablokowane."))return;startTransition(async()=>{try{await post({action:"approve",outputId});setMessage("Inwestycja została zakończona. Dane historyczne pozostają dostępne, a nowe operacyjne przypisania są zablokowane.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function archive(){if(!canManage||!completed)return;setError(null);setMessage(null);if(!window.confirm("Przenieść zakończoną inwestycję do Archiwum? Dokumentacja i cała historia pozostaną dostępne w trybie tylko do odczytu."))return;startTransition(async()=>{try{await post({action:"archive"});setMessage("Inwestycja została przeniesiona do Archiwum. Dokumentacja i historia nie zostały przeniesione ani usunięte — pozostają pod tym samym ID inwestycji.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 const required=requirements.filter(r=>r.required).length;const readyRequired=requirements.filter(r=>r.required&&r.status==="complete").length;const percent=required?Math.round(readyRequired/required*100):0;
 const blockers=n(readiness.blockers);const readinessReady=readiness.ready===true;const canClose=canMutate&&percent===100&&readinessReady;
 const statusLabel=archived?"Archiwalna":completed?"Zakończona":projectStatus==="active"?"Aktywna":projectStatus==="preparation"?"Przygotowanie":projectStatus==="paused"?"Wstrzymana":"W toku";
 const statusCopy=archived?"Dane pozostają dostępne wyłącznie do odczytu.":completed?"Inwestycja jest zakończona i może zostać przeniesiona do Archiwum.":canClose?"Wszystkie warunki są spełnione. Możesz zakończyć inwestycję jednym przyciskiem.":`Do zakończenia wymagane są: pełna checklista (${readyRequired}/${required}) i brak blokerów operacyjnych (${blockers}).`;
 function finishProject(){
  if(!canMutate)return;
  setError(null);setMessage(null);
  if(!canClose){setError(`Nie można jeszcze zakończyć inwestycji. Uzupełnij wymaganą checklistę (${readyRequired}/${required}) i usuń blokery operacyjne (${blockers}).`);return;}
  if(!window.confirm("Zakończyć inwestycję? System automatycznie utworzy aktualną paczkę przekazania, domknie bieżące przypisania pracowników i zablokuje nowe wpisy operacyjne dla tej inwestycji."))return;
  startTransition(async()=>{try{const generated=await post({action:"generate"});if(!generated.id)throw new Error("Nie udało się utworzyć aktualnej paczki przekazania.");await post({action:"approve",outputId:generated.id});setMessage("Inwestycja została zakończona. Aktualna paczka przekazania została utworzona automatycznie, a historia pozostaje dostępna.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});
 }
 const checks=[
  ["Otwarte zadania",n(readiness.openTasks)],["Dokumenty do decyzji",n(readiness.pendingDocuments)],["Wnioski materiałowe",n(readiness.pendingMaterialRequests)],
  ["Zamówienia zakupowe",n(readiness.pendingPurchaseOrders)],["Finanse do rozliczenia",n(readiness.pendingFinance)],["Ruchy magazynowe w szkicu",n(readiness.draftStockMovements)]
 ] as const;
 return <div data-project-lifecycle-closeout="540">
 <section className="pw-submodule-metrics"><article data-tone="positive"><span>Kompletność</span><strong>{percent}%</strong><small>{readyRequired}/{required} wymaganych pozycji</small></article><article data-tone={blockers?"warning":"positive"}><span>Blokery operacyjne</span><strong>{blockers}</strong><small>{readinessReady?"gotowe do zamknięcia":"wymagają wyjaśnienia"}</small></article><article><span>Przypisania do domknięcia</span><strong>{n(readiness.activeAssignments)+n(readiness.activeTeams)}</strong><small>zamykane automatycznie przy zakończeniu</small></article><article><span>Status inwestycji</span><strong>{archived?"Archiwum":completed?"Zakończona":readinessReady&&percent===100?"Gotowa":"W toku"}</strong><small>{archived?"tylko do odczytu":completed?"można archiwizować":"kontrola przed zamknięciem"}</small></article></section>

 <section className="section-band" data-project-status-editor="540"><div className="section-heading"><div><p className="eyebrow">Status inwestycji</p><h2>{statusLabel}</h2><span>{statusCopy}</span></div>{canManage?<div>{completed?<button className="primary-button" disabled={pending} onClick={archive}>{pending?<LoaderCircle className="spin" size={16}/>:<Archive size={16}/>}Przenieś do Archiwum</button>:archived?<span className="status-chip status-chip--positive"><Archive size={14}/>Archiwum</span>:<button className="primary-button" disabled={pending} onClick={finishProject} title={canClose?"Zakończ inwestycję":"Kliknij, aby zobaczyć co trzeba uzupełnić przed zakończeniem"}>{pending?<LoaderCircle className="spin" size={16}/>:<CheckCircle2 size={16}/>}Zakończ inwestycję</button>}</div>:null}</div></section>

 {message?<p className="project-operation-card__success"><CheckCircle2 size={16}/>{message}</p>:null}{error?<p className="project-operation-card__error"><TriangleAlert size={16}/>{error}</p>:null}
 {archived?<p className="project-operation-card__success"><Archive size={16}/><strong>Archiwum inwestycji.</strong> Cała dokumentacja, koszty, godziny, protokoły i historia AI pozostają dostępne pod tym samym projektem, ale dane operacyjne są tylko do odczytu.</p>:completed?<p className="project-operation-card__success"><CheckCircle2 size={16}/><strong>Inwestycja zakończona.</strong> Zniknęła z nowych wyborów operacyjnych.</p>:null}

 {!readOnly?<section className="section-band"><div className="section-heading"><div><p className="eyebrow">Kontrola systemowa</p><h2>Gotowość do zakończenia</h2></div><span className={`status-chip ${readinessReady?"status-chip--positive":"status-chip--warning"}`}>{readinessReady?"Brak blokerów":`${blockers} blokerów`}</span></div><div className="closeout-list">{checks.map(([label,value])=><article key={label}>{value===0?<CheckCircle2 size={18}/>:<TriangleAlert size={18}/>}<div><strong>{label}</strong><span>{value===0?"Brak otwartych pozycji":`${value} pozycji do zamknięcia lub decyzji`}</span></div><span className={`status-chip ${value===0?"status-chip--positive":"status-chip--warning"}`}>{value}</span></article>)}<article><UsersRound size={18}/><div><strong>Aktywne przypisania pracowników / brygad</strong><span>{n(readiness.activeAssignments)+n(readiness.activeTeams)} — nie blokują zamknięcia; system domknie je automatycznie datą zakończenia.</span></div><span className="status-chip">auto</span></article></div></section>:null}

 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Checklista</p><h2>Zakres przekazania</h2></div>{canMutate?<button className="primary-button" disabled={pending||!requirements.length} onClick={generate}>{pending?<LoaderCircle className="spin" size={16}/>:<PackageCheck size={16}/>}Generuj wersję paczki</button>:<ShieldCheck size={22}/>}</div><div className="closeout-list">{requirements.map(item=><article key={item.id}>{item.status==="complete"?<CheckCircle2 size={18}/>:<CircleDashed size={18}/>}<div><small>{item.category}{item.required?" · wymagane":" · opcjonalne"}</small><strong>{item.title}</strong>{item.document_id?<span>Dowód: {documents.find(d=>d.id===item.document_id)?.name??item.document_id}</span>:null}</div><span className={`status-chip ${item.status==="complete"?"status-chip--positive":"status-chip--warning"}`}>{item.status==="complete"?"Kompletne":"Brak"}</span>{canMutate?<button className="secondary-button" disabled={pending} onClick={()=>setRequirement(item,item.status!=="complete")}>{item.status==="complete"?<><RefreshCw size={14}/>Otwórz ponownie</>:<><CheckCircle2 size={14}/>Potwierdź</>}</button>:null}</article>)}{!requirements.length?<div className="empty-state"><ShieldCheck size={25}/><strong>Checklista nie została jeszcze utworzona</strong><span>{canMutate?"Użyj przycisku inicjalizacji nad sekcją.":"Brak checklisty w historii inwestycji."}</span></div>:null}</div></section>

 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Outputs</p><h2>Wersjonowane paczki przekazania</h2></div></div><div className="project-live-records">{outputs.map(output=><article className="project-live-record" key={output.id}><div><strong>{output.title} · v{output.version_number}</strong><p>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(output.generated_at))}</p><small>Status: {output.status}</small></div><div><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=pdf`}><Download size={14}/>PDF</Link><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=json`}><FileJson2 size={14}/>Manifest JSON</Link>{canMutate&&output.status==="ready"?<button className="primary-button" disabled={pending||!canClose} title={!canClose?"Najpierw usuń blokery operacyjne i uzupełnij checklistę":"Zakończ inwestycję"} onClick={()=>approve(output.id)}><ShieldCheck size={14}/>Zatwierdź i zakończ inwestycję</button>:null}</div></article>)}{!outputs.length?<p className="empty-copy">Nie wygenerowano jeszcze żadnej wersji paczki.</p>:null}</div></section>
 </div>;
}
