"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, CircleDashed, Download, FileJson2, LoaderCircle, PackageCheck, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";

type Requirement = { id:string; category:string; title:string; status:string; document_id:string|null; required:boolean };
type DocumentOption = { id:string; name:string };
type Output = { id:string; title:string; version_number:number; status:string; generated_at:string; warnings:unknown };
type Props={projectId:string;canManage:boolean;requirements:Requirement[];documents:DocumentOption[];outputs:Output[]};

export function CloseoutWorkspace({projectId,canManage,requirements,documents,outputs}:Props){
 const router=useRouter();const[pending,startTransition]=useTransition();const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 async function post(body:Record<string,unknown>){const response=await fetch("/api/projects/closeout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,...body})});const result=await response.json() as {error?:string;status?:string;version?:number};if(!response.ok)throw new Error(result.error??"Operacja closeout nie powiodła się.");return result;}
 function setRequirement(item:Requirement,complete:boolean){let documentId=item.document_id??"";if(complete&&!documentId&&documents.length){documentId=window.prompt("Opcjonalnie wklej ID dokumentu dowodowego lub pozostaw puste dla pozycji, które nie wymagają pliku.","")??"";}setError(null);setMessage(null);startTransition(async()=>{try{await post({action:"set_requirement",requirementId:item.id,complete,documentId:documentId||null});setMessage(complete?"Pozycja oznaczona jako kompletna.":"Pozycja ponownie otwarta.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function generate(){setError(null);setMessage(null);startTransition(async()=>{try{const r=await post({action:"generate"});setMessage(`Utworzono paczkę v${r.version} (${r.status}).`);router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 function approve(outputId:string){setError(null);setMessage(null);startTransition(async()=>{try{await post({action:"approve",outputId});setMessage("Paczka została zatwierdzona, a inwestycja oznaczona jako zakończona.");router.refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}});}
 const complete=requirements.filter(r=>r.status==="complete").length;const required=requirements.filter(r=>r.required).length;const readyRequired=requirements.filter(r=>r.required&&r.status==="complete").length;const percent=required?Math.round(readyRequired/required*100):0;
 return <>
 <section className="pw-submodule-metrics"><article data-tone="positive"><span>Kompletność</span><strong>{percent}%</strong><small>{readyRequired}/{required} wymaganych pozycji</small></article><article><span>Wszystkie pozycje</span><strong>{requirements.length}</strong><small>{complete} gotowych</small></article><article><span>Wersje paczki</span><strong>{outputs.length}</strong><small>niezmienne snapshoty</small></article><article><span>Status końcowy</span><strong>{outputs.some(o=>o.status==="approved")?"Zatwierdzony":percent===100?"Gotowy":"W toku"}</strong><small>po zatwierdzeniu paczki</small></article></section>
 {message?<p className="project-operation-card__success"><CheckCircle2 size={16}/>{message}</p>:null}{error?<p className="project-operation-card__error"><TriangleAlert size={16}/>{error}</p>:null}
 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Checklista</p><h2>Zakres przekazania</h2></div>{canManage?<button className="primary-button" disabled={pending||!requirements.length} onClick={generate}>{pending?<LoaderCircle className="spin" size={16}/>:<PackageCheck size={16}/>}Generuj wersję paczki</button>:<ShieldCheck size={22}/>}</div><div className="closeout-list">{requirements.map(item=><article key={item.id}>{item.status==="complete"?<CheckCircle2 size={18}/>:<CircleDashed size={18}/>}<div><small>{item.category}{item.required?" · wymagane":" · opcjonalne"}</small><strong>{item.title}</strong>{item.document_id?<span>Dowód: {documents.find(d=>d.id===item.document_id)?.name??item.document_id}</span>:null}</div><span className={`status-chip ${item.status==="complete"?"status-chip--positive":"status-chip--warning"}`}>{item.status==="complete"?"Kompletne":"Brak"}</span>{canManage?<button className="secondary-button" disabled={pending} onClick={()=>setRequirement(item,item.status!=="complete")}>{item.status==="complete"?<><RefreshCw size={14}/>Otwórz ponownie</>:<><CheckCircle2 size={14}/>Potwierdź</>}</button>:null}</article>)}{!requirements.length?<div className="empty-state"><ShieldCheck size={25}/><strong>Checklista nie została jeszcze utworzona</strong><span>Użyj przycisku inicjalizacji nad sekcją.</span></div>:null}</div></section>
 <section className="section-band"><div className="section-heading"><div><p className="eyebrow">Outputs</p><h2>Wersjonowane paczki przekazania</h2></div></div><div className="project-live-records">{outputs.map(output=><article className="project-live-record" key={output.id}><div><strong>{output.title} · v{output.version_number}</strong><p>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(output.generated_at))}</p><small>Status: {output.status}</small></div><div><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=pdf`}><Download size={14}/>PDF</Link><Link className="secondary-button" href={`/api/projects/closeout?projectId=${projectId}&outputId=${output.id}&format=json`}><FileJson2 size={14}/>Manifest JSON</Link>{canManage&&output.status==="ready"?<button className="primary-button" disabled={pending} onClick={()=>approve(output.id)}><ShieldCheck size={14}/>Zatwierdź i zamknij</button>:null}</div></article>)}{!outputs.length?<p className="empty-copy">Nie wygenerowano jeszcze żadnej wersji paczki.</p>:null}</div></section>
 </>;
}
