import Link from "next/link";
import { AlertTriangle, ArrowRight, Bot, Boxes, CheckCircle2, ClipboardCheck, FileClock, FileSearch, GitCompareArrows, HardHat, Network, PackageCheck, ShieldAlert, Sparkles, UserCheck, WalletCards } from "lucide-react";
import type { InvestmentAutopilotSnapshot } from "@/lib/investments/autopilot";
import { AutopilotRunButton } from "@/components/projects/autopilot-run-button";
import styles from "./investment-autopilot.module.css";

function money(value: number) { return new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN", maximumFractionDigits: 0 }).format(value); }
function ownerLabel(owner: "ai" | "human" | "field") { return owner === "ai" ? "Octopus może wykonać" : owner === "field" ? "Do wykonania na budowie" : "Potrzebna decyzja"; }
function ownerIcon(owner: "ai" | "human" | "field") { return owner === "ai" ? Bot : owner === "field" ? HardHat : UserCheck; }

export function InvestmentAutopilotCenter({ projectId, workspaceId, snapshot, canRun, financeAllowed, warehouseAllowed }: { projectId: string; workspaceId: string; snapshot: InvestmentAutopilotSnapshot; canRun: boolean; financeAllowed: boolean; warehouseAllowed: boolean }) {
  const base = `/workspace/projects/${projectId}`;
  return <section id="autopilot" className={styles.center}>
    <div className={styles.hero}>
      <div><p className={styles.kicker}><Sparkles size={15} /> Investment Autopilot</p><h2>Octopus ustala, co trzeba zrobić — i wykonuje bezpieczne czynności automatycznie</h2><p>Dokumentacja → Project DNA → wymagania → szkice WM/protokołów/harmonogramu → kontrola rewizji → zgodność z BOQ, finansami i magazynem.</p></div>
      <div className={styles.health} data-state={snapshot.healthLabel}><small>Project Health</small><strong>{snapshot.healthScore}</strong><span>{snapshot.healthLabel}</span></div>
      {canRun ? <AutopilotRunButton projectId={projectId} /> : <small className={styles.readOnly}>Tryb tylko do odczytu</small>}
    </div>

    <div className={styles.metrics}>
      <article><Bot size={18} /><span><small>AI może zrobić teraz</small><strong>{snapshot.aiCanDoCount}</strong></span></article>
      <article><UserCheck size={18} /><span><small>Decyzje człowieka</small><strong>{snapshot.humanDecisionCount}</strong></span></article>
      <article><HardHat size={18} /><span><small>Czynności na budowie</small><strong>{snapshot.fieldActionCount}</strong></span></article>
      <article><ShieldAlert size={18} /><span><small>Blokady</small><strong>{snapshot.blockerCount}</strong></span></article>
    </div>

    <div className={styles.nextStep}><div className={styles.nextIcon}>{snapshot.nextMission?.owner === "ai" ? <Bot size={22} /> : snapshot.nextMission?.owner === "field" ? <HardHat size={22} /> : <AlertTriangle size={22} />}</div><div><small>Następny krok wyliczony z aktualnego stanu inwestycji</small><strong>{snapshot.nextMission?.title ?? "Brak pilnych działań"}</strong><p>{snapshot.nextMission?.description ?? "Octopus nie wykrył obecnie krytycznych braków."}</p></div>{snapshot.nextMission ? <Link href={snapshot.nextMission.href}>{snapshot.nextMission.actionLabel} <ArrowRight size={14} /></Link> : null}</div>

    <div className={styles.twoColumns}>
      <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><ClipboardCheck size={15} /> Mission Engine</p><h3>Co trzeba zrobić</h3></div><span>{snapshot.missions.length} aktywnych</span></div><div className={styles.missionList}>{snapshot.missions.slice(0,12).map((mission)=>{const Icon=ownerIcon(mission.owner);return <Link href={mission.href} className={styles.mission} data-priority={mission.priority} key={mission.id}><span className={styles.missionIcon}><Icon size={16}/></span><span className={styles.missionMain}><small>{ownerLabel(mission.owner)} · {mission.priority}</small><strong>{mission.title}</strong><p>{mission.description}</p></span><span className={styles.missionAction}>{mission.actionLabel}<ArrowRight size={13}/></span></Link>})}{!snapshot.missions.length?<p className={styles.empty}><CheckCircle2 size={18}/> Brak aktywnych misji. Stan inwestycji jest spójny.</p>:null}</div></article>
      <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><GitCompareArrows size={15}/> Change Radar 2.0</p><h3>Skutki nowych rewizji</h3></div><span>{snapshot.changeRadar.length} zmian</span></div><div className={styles.changeList}>{snapshot.changeRadar.slice(0,8).map((change)=><div className={styles.change} data-risk={change.riskLevel} key={change.id}><div><strong>{change.summary}</strong><small>Cel: {change.targetType} · ryzyko: {change.riskLevel}</small></div><ul>{change.consequences.map((item)=><li key={item}>{item}</li>)}</ul></div>)}{!snapshot.changeRadar.length?<p className={styles.empty}><CheckCircle2 size={18}/> Brak niezatwierdzonych skutków rewizji.</p>:null}</div></article>
    </div>

    <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><Network size={15}/> Matryca instalacji</p><h3>Projekt → BOQ → materiały → plan → próby → dowody</h3></div><span>{snapshot.installations.length} systemów</span></div><div className={styles.matrixWrap}><table className={styles.matrix}><thead><tr><th>Instalacja</th><th>Wiedza</th><th>BOQ</th><th>WM</th><th>Plan</th><th>Protokoły</th><th>Dowody</th><th>Gotowość</th></tr></thead><tbody>{snapshot.installations.map((row)=><tr key={row.name} data-state={row.state}><td><strong>{row.name}</strong><small>{row.wbsCodes.length?`WBS ${row.wbsCodes.join(", ")}`:"bez kodu WBS"}</small></td><td>{row.materials+row.devices}<small>{row.materials} mat. · {row.devices} urz.</small></td><td>{row.boqItems}</td><td>{row.approvedMaterialRequests}/{row.materialRequests}</td><td>{row.scheduleActivities}</td><td>{row.protocolsClosed}/{row.protocolsRequired}</td><td>{row.evidenceComplete}/{row.evidenceRequired}</td><td><span className={styles.readiness}><i style={{width:`${row.readiness}%`}}/></span><b>{row.readiness}%</b></td></tr>)}</tbody></table>{!snapshot.installations.length?<p className={styles.empty}>Matryca powstanie po rozpoznaniu instalacji, WBS lub BOQ.</p>:null}</div></article>

    <div className={styles.threeColumns}>
      <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><FileSearch size={15}/> Genealogia danych</p><h3>Czy wiadomo, skąd pochodzą dane?</h3></div></div><div className={styles.lineageScore}><strong>{snapshot.lineage.sourceCoveragePercent}%</strong><span>faktów ma źródło</span></div><dl className={styles.stats}><div><dt>Dokumenty</dt><dd>{snapshot.lineage.documents}</dd></div><div><dt>AI gotowe/review</dt><dd>{snapshot.lineage.readyDocuments}</dd></div><div><dt>Fakty Brain</dt><dd>{snapshot.lineage.facts}</dd></div><div><dt>Fakty ze źródłem</dt><dd>{snapshot.lineage.sourcedFacts}</dd></div></dl><Link className={styles.textLink} href={`${base}/brain`}>Otwórz Project DNA <ArrowRight size={14}/></Link></article>
      <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><FileClock size={15}/> Decyzje AI</p><h3>Lokalna kolejka inwestycji</h3></div><span>{snapshot.decisions.length}</span></div><div className={styles.decisionList}>{snapshot.decisions.slice(0,6).map((item)=><Link href={`/workspace/companies/${workspaceId}/ai-inbox`} key={`${item.category}:${item.id}`}><span><strong>{item.title}</strong><small>{item.subtitle} · {item.status}</small></span><b>{item.confidence==null?"—":`${Math.round(item.confidence*100)}%`}</b></Link>)}</div>{!snapshot.decisions.length?<p className={styles.empty}><CheckCircle2 size={18}/> Kolejka decyzji tej inwestycji jest czysta.</p>:null}</article>
      <article className={styles.panel}><div className={styles.panelHead}><div><p className={styles.kicker}><WalletCards size={15}/> Reconciliation</p><h3>Projekt ↔ BOQ ↔ zakup ↔ magazyn</h3></div></div><dl className={styles.stats}><div><dt>Odebrany BOQ</dt><dd>{money(snapshot.reconciliation.acceptedWorkValue)}</dd></div><div><dt>Sprzedaż przypisana</dt><dd>{financeAllowed?money(snapshot.reconciliation.salesNet):"chronione"}</dd></div><div><dt>Zakupy przypisane</dt><dd>{financeAllowed?money(snapshot.reconciliation.purchaseNet):"chronione"}</dd></div><div><dt>WZ/RW/MM</dt><dd>{warehouseAllowed?snapshot.reconciliation.warehouseDocuments:"chronione"}</dd></div></dl><div className={styles.findings}>{snapshot.reconciliation.findings.slice(0,5).map((item)=><div data-severity={item.severity} key={item.id}><AlertTriangle size={14}/><span><strong>{item.title}</strong><small>{item.description}</small></span></div>)}</div>{!snapshot.reconciliation.findings.length?<p className={styles.empty}><PackageCheck size={18}/> Brak wykrytych rozbieżności w dostępnych danych.</p>:null}</article>
    </div>

    <div className={styles.footerFlow}><Boxes size={17}/><span><strong>Zasada działania:</strong> Brain przechowuje prawdę → Mission Engine ustala obowiązki → Autopilot tworzy bezpieczne szkice → Change Radar unieważnia nieaktualne założenia → Control 360° sprawdza zgodność wykonania.</span></div>
  </section>;
}
