"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowDown, ArrowRight, ArrowUp, CalendarClock, CheckCircle2, CircleDollarSign, HeartPulse, Mail, RefreshCcw, ShieldCheck, UsersRound } from "lucide-react";

type Row=Record<string,unknown>;
type Data={snapshot:Record<string,unknown>;anomalies:Row[];correspondence:Row[];resources:Row[];employees:Row[]};

const money=(v:unknown)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:0}).format(Number(v??0));
const num=(v:unknown)=>new Intl.NumberFormat("pl-PL",{maximumFractionDigits:1}).format(Number(v??0));
function obj(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function arr(v:unknown){return Array.isArray(v)?v as Row[]:[];}

export function ProjectCommandCenter({projectId,data,canManage}:{projectId:string;data:Data;canManage:boolean}){
 const router=useRouter(); const [pending,startTransition]=useTransition(); const [message,setMessage]=useState<string|null>(null); const s=data.snapshot;
 const forecast=obj(s.forecast),schedule=obj(s.schedule),anomalyStats=obj(s.anomalies),quality=obj(s.quality),health=obj(s.projectHealth),financeCoverage=obj(s.financeCoverage),confidence=obj(health.dataConfidence),cash=arr(s.cashflow13w),lessons=arr(s.crossProjectKnowledge),deductions=arr(health.deductions);
 async function action(actionName:string,payload:Record<string,unknown>){setMessage(null);const response=await fetch("/api/projects/command-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,action:actionName,payload})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"Operacja nie powiodła się.");setMessage("Zapisano. Command Center został odświeżony.");startTransition(()=>router.refresh());}
 function submit(actionName:string){return async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await action(actionName,Object.fromEntries(form.entries()));event.currentTarget.reset();}catch(error){setMessage(error instanceof Error?error.message:"Błąd zapisu.");}};}
 return <section className="section-band project-command-center">
  <div className="section-heading"><div><p className="eyebrow">Project Octopus 1.1</p><h2>Command Center</h2><p>Cash flow, zasoby, korespondencja, anomalie, wyjaśnialny Project Health i prognoza w jednym operacyjnym widoku.</p></div><span>{pending?<RefreshCcw size={16}/>:<CheckCircle2 size={16}/>} stan operacyjny</span></div>
  {message?<p className="command-message">{message}</p>:null}
  <div className="command-next-action"><HeartPulse size={21}/><div><small>Project Health · wskaźnik operacyjny · {String(health.status??"—")}</small><strong>{String(health.score??"—")}/100</strong><p>{String(s.nextAction??"Brak wyznaczonego następnego kroku.")}</p><span>Wiarygodność danych finansowych: {num(financeCoverage.allocationCoveragePct)}% · {String(confidence.status??"—")}</span></div><ArrowRight size={20}/></div>
  {deductions.length>0?<details className="module-panel"><summary><strong>Dlaczego wynik wynosi {String(health.score??"—")}/100?</strong></summary><div className="live-record-list">{deductions.map((item)=><div key={String(item.code)} className="command-row"><div><strong>{String(item.label)}</strong><span>{String(item.count)} zdarzeń / pozycji</span></div><b>−{String(item.points)} pkt</b></div>)}</div></details>:<div className="command-message"><ShieldCheck size={16}/> Brak potrąceń w bieżącym wskaźniku operacyjnym.</div>}
  <div className="command-kpis">
   <article><CircleDollarSign/><small>Kontrakt</small><strong>{money(s.contractValue)}</strong><span>Koszt przypisany {money(s.actualCost)} · zobowiązania {money(s.committedCost)}</span><span>Pokrycie alokacją {num(financeCoverage.allocationCoveragePct)}%</span></article>
   <article><CalendarClock/><small>Prognoza końca</small><strong>{String(forecast.finishDate??schedule.latestOpenFinish??"—")}</strong><span>EAC {money(forecast.eac)} · marża {money(forecast.margin)}</span></article>
   <article><AlertTriangle/><small>Anomalie</small><strong>{String(anomalyStats.open??0)}</strong><span>{String(anomalyStats.critical??0)} krytycznych · {String(quality.missingEvidence??0)} braków dowodowych</span></article>
   <article><CheckCircle2/><small>Odebrany przerób</small><strong>{money(s.acceptedProgressValue)}</strong><span>{String(schedule.overdueCritical??0)} opóźnionych zadań krytycznych</span></article>
  </div>
  <details className="module-panel" open><summary><strong>13-tygodniowy cash flow · bazowy i ostrożny</strong></summary><div className="command-cashflow">{cash.map((w)=><article key={String(w.weekStart)}><small>{String(w.weekStart)}</small><span><ArrowUp size={14}/> {money(w.inflow)}</span><span><ArrowDown size={14}/> {money(w.outflow)}</span><b>{money(w.net)}</b><small>ostrożny: {money(w.cautiousNet)}</small></article>)}</div><p className="empty-copy">Scenariusz ostrożny przyjmuje 85% planowanych wpływów. To bufor operacyjny, a nie obietnica terminu płatności.</p></details>
  <div className="control-dashboard-grid">
   <article className="module-panel"><div className="module-panel__heading"><AlertTriangle size={20}/><div><p className="eyebrow">Anomaly Engine</p><h3>Odchylenia wymagające uwagi</h3></div></div><div className="live-record-list">{data.anomalies.filter(a=>a.status!=="resolved").map(a=><div key={String(a.id)} className="command-row"><div><small>{String(a.category)} · {String(a.severity)} · od {String(a.first_detected_at??a.detected_at??"").slice(0,10)}</small><strong>{String(a.title)}</strong><span>{String(a.detail??"")}</span></div>{canManage?<span><button onClick={()=>action("anomaly_acknowledge",{anomalyId:a.id})}>Przyjmij</button><button onClick={()=>action("anomaly_resolve",{anomalyId:a.id})}>Rozwiąż</button></span>:null}</div>)}{!data.anomalies.some(a=>a.status!=="resolved")?<p className="empty-copy">Brak aktywnych anomalii.</p>:null}</div></article>
   <article className="module-panel"><div className="module-panel__heading"><UsersRound size={20}/><div><p className="eyebrow">Resource Planner</p><h3>Plan zasobów</h3></div></div>{canManage?<form onSubmit={submit("resource_plan_create")} className="command-form"><select name="employeeId" defaultValue=""><option value="">Rola bez wskazanej osoby</option>{data.employees.map(e=><option key={String(e.id)} value={String(e.id)}>{String(e.first_name)} {String(e.last_name)}</option>)}</select><input name="role" placeholder="Rola" required/><input type="date" name="weekStart" required/><input name="plannedHours" inputMode="decimal" placeholder="Godziny"/><input name="allocationPercent" inputMode="decimal" placeholder="%"/><button>Zaplanuj</button></form>:null}<div className="live-record-list">{data.resources.slice(0,12).map(r=><div key={String(r.id)} className="command-row"><div><strong>{String(r.role)}</strong><span>{String(r.week_start)} · {num(r.planned_hours)} h · {num(r.allocation_percent)}%</span></div></div>)}</div></article>
   <article className="module-panel"><div className="module-panel__heading"><Mail size={20}/><div><p className="eyebrow">Korespondencja i rewizje</p><h3>Rejestr komunikacji</h3></div></div>{canManage?<form onSubmit={submit("correspondence_create")} className="command-form"><select name="direction" defaultValue="incoming"><option value="incoming">Przychodząca</option><option value="outgoing">Wychodząca</option><option value="internal">Wewnętrzna</option></select><input name="subject" placeholder="Temat" required/><input name="counterparty" placeholder="Strona / kontrahent"/><input name="referenceNumber" placeholder="Nr pisma / RFI / rewizji"/><input type="datetime-local" name="dueAt"/><button>Dodaj</button></form>:null}<div className="live-record-list">{data.correspondence.slice(0,10).map(c=><div key={String(c.id)} className="command-row"><div><small>{String(c.direction)} · {String(c.correspondence_type)}</small><strong>{String(c.subject)}</strong><span>{String(c.reference_number??"")} {c.due_at?`· termin ${String(c.due_at).slice(0,10)}`:""}</span></div></div>)}</div></article>
   <article className="module-panel"><div className="module-panel__heading"><CheckCircle2 size={20}/><div><p className="eyebrow">Wiedza firmy</p><h3>Doświadczenia z innych inwestycji</h3></div></div><div className="live-record-list">{lessons.map(l=><div key={String(l.id)} className="command-row"><div><small>{String(l.entry_type)}</small><strong>{String(l.title)}</strong><span>{String(l.summary)}</span></div></div>)}{lessons.length===0?<p className="empty-copy">Brak zatwierdzonej wiedzy międzyprojektowej.</p>:null}</div></article>
  </div>
 </section>;
}
