"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Check, GitBranch, Link2, LoaderCircle, PackagePlus, RefreshCcw, ShoppingCart, X } from "lucide-react";

type Row=Record<string,unknown>;
type ReconciliationData={graph:Record<string,unknown>;links:Row[];orders:Row[];requests:Row[];counterparties:Row[];stockItems:Row[];boqItems:Row[]};
function obj(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
const money=(value:unknown)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:0}).format(Number(value??0));

export function ProjectReconciliationGraph({projectId,data,canManage,canOrder}:{projectId:string;data:ReconciliationData;canManage:boolean;canOrder:boolean}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [message,setMessage]=useState<string|null>(null);
 const graph=data.graph,boq=obj(graph.boq),costs=obj(graph.costs),commitments=obj(graph.commitments),progress=obj(graph.progress),orders=obj(graph.orders),links=obj(graph.links);
 async function call(action:string,extra:Record<string,unknown>={}){setMessage(null);const response=await fetch("/api/projects/reconciliation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,action,...extra})});const payload=await response.json() as {error?:string;candidates?:number;orderId?:string};if(!response.ok)throw new Error(payload.error??"Operacja nie powiodła się.");setMessage(action==="auto_match"?`Przeanalizowano graf. Kandydatów: ${payload.candidates??0}.`:action==="purchase_order_create"?`Utworzono zamówienie ${payload.orderId??""}. Zobowiązanie i łańcuch materiałowy zaktualizowano automatycznie.`:"Decyzja została zapisana.");startTransition(()=>router.refresh());}
 async function createOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;try{await call("purchase_order_create",{payload:Object.fromEntries(new FormData(form).entries())});form.reset();}catch(error){setMessage(error instanceof Error?error.message:"Nie udało się utworzyć zamówienia.");}}
 return <section className="section-band reconciliation-graph">
  <div className="section-heading"><div><p className="eyebrow">Reconciliation 0.9.4</p><h2>Graf koszt ↔ materiał ↔ BOQ/WBS</h2><p>Śledzenie od wniosku materiałowego i zamówienia przez fakturę oraz magazyn do wykonania i odbioru.</p></div>{canManage?<button onClick={()=>call("auto_match").catch(e=>setMessage(e.message))} disabled={pending}>{pending?<LoaderCircle size={16}/>:<RefreshCcw size={16}/>} Dopasuj automatycznie</button>:null}</div>
  {message?<p className="command-message">{message}</p>:null}
  <div className="command-kpis"><article><GitBranch/><small>BOQ plan</small><strong>{money(boq.plannedValue)}</strong><span>{String(boq.items??0)} pozycji</span></article><article><Link2/><small>Koszt rzeczywisty</small><strong>{money(costs.actualCost)}</strong><span>{String(costs.boqLinked??0)} alokacji do BOQ · {String(costs.wbsLinked??0)} do WBS</span></article><article><ShoppingCart/><small>Zamówienia</small><strong>{money(orders.orderedValue)}</strong><span>{String(orders.ordersCount??0)} zamówień · zobowiązania {money(commitments.committedCost)}</span></article><article><Check/><small>Odebrany przerób</small><strong>{money(progress.acceptedValue)}</strong><span>{String(links.approved??0)} zatwierdzonych powiązań</span></article></div>
  {canOrder?<details className="module-panel" open><summary><strong>Utwórz zamówienie z łańcucha materiałowego</strong></summary><form className="command-form reconciliation-order-form" onSubmit={createOrder}><label>Wniosek materiałowy<select name="sourceRequestId" defaultValue=""><option value="">Bez bezpośredniego WM</option>{data.requests.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.title)} · {String(row.status)}</option>)}</select></label><label>Dostawca<select name="counterpartyId" defaultValue=""><option value="">Bez wskazanego dostawcy</option>{data.counterparties.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.name)}</option>)}</select></label><label>Numer zamówienia<input name="orderNumber" required placeholder="ZAM/2026/001"/></label><label>Data zamówienia<input name="orderedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Termin dostawy<input name="expectedAt" type="date"/></label><label>Kartoteka magazynowa<select name="stockItemId" defaultValue=""><option value="">Bez kartoteki</option>{data.stockItems.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.sku??"—")} · {String(row.name)}</option>)}</select></label><label>Pozycja BOQ<select name="boqItemId" defaultValue=""><option value="">Bez powiązania BOQ</option>{data.boqItems.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.item_number??"BOQ")} · {String(row.description)}</option>)}</select></label><label>Opis pozycji<input name="description" required placeholder="Rura PP DN110"/></label><label>Ilość<input name="quantity" inputMode="decimal" required placeholder="20"/></label><label>Jednostka<input name="unit" placeholder="m / szt."/></label><label>Cena jednostkowa<input name="unitPrice" inputMode="decimal" placeholder="42,50"/></label><button disabled={pending}><PackagePlus size={16}/> Utwórz zamówienie</button></form></details>:null}
  <details className="module-panel"><summary><strong>Aktywne zamówienia · {data.orders.length}</strong></summary><div className="live-record-list">{data.orders.map(row=><div key={String(row.id)} className="command-row"><div><small>{String(row.status)} · zamówiono {String(row.ordered_at??"—")} · dostawa {String(row.expected_at??"—")}</small><strong>{String(row.order_number)}</strong><span>{money(row.total_amount)} {row.source_request_id?"· połączone z WM":""}</span></div></div>)}{data.orders.length===0?<p className="empty-copy">Brak zamówień dla inwestycji.</p>:null}</div></details>
  <details className="module-panel"><summary><strong>Powiązania do decyzji · {String(links.proposed??0)}</strong></summary><div className="live-record-list">{data.links.filter(row=>row.status==="proposed").slice(0,25).map(row=><div key={String(row.id)} className="command-row"><div><small>{String(row.source_type)} → {String(row.target_type)}</small><strong>{Math.round(Number(row.confidence??0)*100)}% zgodności</strong><span>{String(row.relation_type)}</span></div>{canManage?<span><button onClick={()=>call("approve_link",{linkId:row.id}).catch(e=>setMessage(e.message))}><Check size={14}/> Zatwierdź</button><button onClick={()=>call("reject_link",{linkId:row.id}).catch(e=>setMessage(e.message))}><X size={14}/> Odrzuć</button></span>:null}</div>)}{!data.links.some(row=>row.status==="proposed")?<p className="empty-copy">Brak niezatwierdzonych dopasowań.</p>:null}</div></details>
 </section>;
}
