"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Check, GitBranch, Link2, LoaderCircle, PackageCheck, PackagePlus, RefreshCcw, ShoppingCart, TrendingUp, X } from "lucide-react";

type Row=Record<string,unknown>;
type ReconciliationData={graph:Record<string,unknown>;links:Row[];orders:Row[];requests:Row[];counterparties:Row[];stockItems:Row[];boqItems:Row[];matches:Row[];deviations:Row[];prices:Row[]};
function obj(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
const money=(value:unknown)=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:2}).format(Number(value??0));
const num=(value:unknown,digits=1)=>new Intl.NumberFormat("pl-PL",{maximumFractionDigits:digits}).format(Number(value??0));

export function ProjectReconciliationGraph({projectId,data,canManage,canOrder}:{projectId:string;data:ReconciliationData;canManage:boolean;canOrder:boolean}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [message,setMessage]=useState<string|null>(null);
 const graph=data.graph,boq=obj(graph.boq),costs=obj(graph.costs),commitments=obj(graph.commitments),progress=obj(graph.progress),orders=obj(graph.orders),links=obj(graph.links),match=obj(graph.procurementMatch),deviations=obj(graph.deviations);
 const approvedRequests=data.requests.filter(row=>String(row.status)==="approved");
 async function call(action:string,extra:Record<string,unknown>={}){setMessage(null);const response=await fetch("/api/projects/reconciliation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,action,...extra})});const payload=await response.json() as {error?:string;candidates?:number;orderId?:string;procurementTraceId?:string};if(!response.ok)throw new Error(payload.error??"Operacja nie powiodła się.");setMessage(action==="auto_match"?`Przeanalizowano graf. Kandydatów: ${payload.candidates??0}.`:action==="purchase_order_create"?`Utworzono zamówienie ${payload.orderId??""}. Ślad ${payload.procurementTraceId??""} łączy WM → PO → PZ → fakturę, a commitment będzie redukowany przez uzgodnione faktury.`:"Decyzja została zapisana atomowo i przeniesiona do kosztu/BOQ.");startTransition(()=>router.refresh());}
 async function createOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;try{await call("purchase_order_create",{payload:Object.fromEntries(new FormData(form).entries())});form.reset();}catch(error){setMessage(error instanceof Error?error.message:"Nie udało się utworzyć zamówienia.");}}
 return <section className="section-band reconciliation-graph">
  <div className="section-heading"><div><p className="eyebrow">Enterprise reconciliation</p><h2>Graf koszt ↔ materiał ↔ BOQ/WBS</h2><p>Ten sam zakup przechodzi przez zatwierdzony WM, PO, PZ i fakturę. Zakup bezpośredni staje się kosztem z faktury; zakup na magazyn centralny staje się kosztem budowy dopiero przy RW.</p></div>{canManage?<button onClick={()=>call("auto_match").catch(e=>setMessage(e.message))} disabled={pending}>{pending?<LoaderCircle size={16}/>:<RefreshCcw size={16}/>} Dopasuj BOQ</button>:null}</div>
  {message?<p className="command-message">{message}</p>:null}
  <div className="command-kpis">
   <article><GitBranch/><small>BOQ plan</small><strong>{money(boq.plannedValue)}</strong><span>{String(boq.items??0)} pozycji</span></article>
   <article><Link2/><small>Koszt rzeczywisty netto</small><strong>{money(costs.actualCost)}</strong><span>FV bezpośrednie {money(costs.invoiceNet)} · RW z magazynu {money(costs.inventoryIssuedCost)} · robocizna {money(costs.laborCost)} · flota {money(Number(costs.fuelOperational??0)+Number(costs.vehicleKmCost??0))}</span></article>
   <article><ShoppingCart/><small>Pozostałe zobowiązania</small><strong>{money(commitments.committedCost)}</strong><span>pierwotnie {money(commitments.originalCost)} · rozpoznano fakturami {money(commitments.recognizedCost)}</span></article>
   <article><PackageCheck/><small>3-way match</small><strong>{String(match.matched??0)}</strong><span>{String(match.review??0)} do kontroli · {String(deviations.open??0)} odstępstw</span></article>
  </div>
  <div className="command-kpis command-kpis--secondary"><article><Check/><small>Odebrany przerób</small><strong>{money(progress.acceptedValue)}</strong><span>{String(links.approved??0)} zatwierdzonych powiązań</span></article><article><PackagePlus/><small>Wydanie materiałów</small><strong>{money(costs.materialConsumptionValue)}</strong><span>wartość logistyki/zużycia; do Actual trafia tylko część z zapasu centralnego, nie zakup bezpośredni</span></article><article><AlertTriangle/><small>Otwarte odstępstwa</small><strong>{String(deviations.open??0)}</strong><span>{String(deviations.critical??0)} krytycznych</span></article><article><TrendingUp/><small>Cash zapłacony brutto</small><strong>{money(costs.cashPaidGross)}</strong><span>cash flow oddzielony od kosztu netto</span></article></div>
  {canOrder?<details className="module-panel" open><summary><strong>Utwórz zamówienie z łańcucha materiałowego</strong></summary><p className="empty-copy">Standardowe PO wymaga zatwierdzonego WM i nie pozwoli zamówić innej kartoteki/BOQ niż zatwierdzona we wniosku. Bez WM powstaje jawne odstępstwo.</p><form className="command-form reconciliation-order-form" onSubmit={createOrder}><label>Zatwierdzony WM<select name="sourceRequestId" defaultValue=""><option value="">Zakup awaryjny bez WM — utworzy odstępstwo</option>{approvedRequests.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.title)}</option>)}</select></label><label>Cel dostawy<select name="destinationMode" defaultValue="direct_project"><option value="direct_project">Bezpośrednio na inwestycję — faktura jest kosztem budowy</option><option value="central_stock">Magazyn centralny — koszt budowy dopiero przy RW</option></select></label><label>Dostawca<select name="counterpartyId" defaultValue=""><option value="">Bez wskazanego dostawcy</option>{data.counterparties.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.name)}</option>)}</select></label><label>Numer zamówienia<input name="orderNumber" required placeholder="ZAM/2026/001"/></label><label>Data zamówienia<input name="orderedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Termin dostawy<input name="expectedAt" type="date"/></label><label>Kartoteka magazynowa<select name="stockItemId" defaultValue=""><option value="">Bez kartoteki / do rozpoznania</option>{data.stockItems.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.sku??"—")} · {String(row.name)}</option>)}</select></label><label>Pozycja BOQ<select name="boqItemId" defaultValue=""><option value="">Bez powiązania BOQ</option>{data.boqItems.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.item_number??"BOQ")} · {String(row.description)}</option>)}</select></label><label>Opis pozycji<input name="description" required placeholder="Rura PP DN110"/></label><label>Ilość<input name="quantity" inputMode="decimal" required placeholder="20"/></label><label>Jednostka<input name="unit" placeholder="m / szt."/></label><label>Cena jednostkowa netto<input name="unitPrice" inputMode="decimal" placeholder="42,50"/></label><button disabled={pending}><PackagePlus size={16}/> Utwórz zamówienie</button></form></details>:null}
  <details className="module-panel"><summary><strong>Aktywne zamówienia · {data.orders.length}</strong></summary><div className="live-record-list">{data.orders.map(row=><div key={String(row.id)} className="command-row"><div><small>{String(row.status)} · zamówiono {String(row.ordered_at??"—")} · dostawa {String(row.expected_at??"—")}</small><strong>{String(row.order_number)}</strong><span>{money(row.total_amount)} {row.source_request_id?"· zatwierdzony WM":row.emergency_override?"· zakup awaryjny / odstępstwo":""}{row.destination_mode?` · ${row.destination_mode==="central_stock"?"magazyn centralny":"bezpośrednio na budowę"}`:""}</span></div></div>)}{data.orders.length===0?<p className="empty-copy">Brak zamówień dla inwestycji.</p>:null}</div></details>
  <details className="module-panel" open={data.matches.some(row=>row.status==="review")}><summary><strong>3-way match · {data.matches.filter(row=>row.status==="review").length} do kontroli</strong></summary><div className="live-record-list">{data.matches.slice(0,30).map(row=>{const warnings=Array.isArray(row.warnings)?row.warnings.map(String):[];return <div key={String(row.id)} className="command-row"><div><small>{String(row.status)} · PO {num(row.ordered_quantity)} · PZ {num(row.received_quantity)} · FV {num(row.invoiced_quantity)}</small><strong>Cena PO {money(row.ordered_unit_price)} → FV {money(row.invoiced_unit_price)}</strong><span>{row.price_variance_percent==null?"":`Δ ceny ${num(row.price_variance_percent)}% · `}{warnings.join(" · ")||"Ilość i cena zgodne."}</span></div></div>})}{data.matches.length===0?<p className="empty-copy">Brak materiałowych pozycji do 3-way match.</p>:null}</div></details>
  <details className="module-panel" open={data.deviations.some(row=>row.status==="open")}><summary><strong>Odstępstwa procesu · {data.deviations.filter(row=>row.status==="open").length} otwartych</strong></summary><div className="live-record-list">{data.deviations.slice(0,30).map(row=><div key={String(row.id)} className="command-row"><div><small>{String(row.severity)} · {String(row.deviation_type)} · {String(row.status)}</small><strong>{String(row.title)}</strong><span>{String(row.detail??row.resolution_note??"Brak dodatkowego opisu.")}</span></div></div>)}{data.deviations.length===0?<p className="empty-copy">Brak odstępstw procesu.</p>:null}</div></details>
  <details className="module-panel"><summary><strong>Historia cen · {data.prices.length} zakupów</strong></summary><div className="live-record-list">{data.prices.slice(0,30).map((row,index)=><div key={`${String(row.sourceId)}-${index}`} className="command-row"><div><small>{String(row.date??"—")} · {String(row.supplier??"dostawca nieznany")} · {String(row.canonicalStage??row.sourceType??"")}</small><strong>{String(row.stockName??"Materiał")}</strong><span>{money(row.unitPriceNet)} / {String(row.unit??"j.m.")}{row.changePercent==null?"":` · zmiana ${num(row.changePercent)}%`}{row.orderedPrice!=null?` · PO ${money(row.orderedPrice)}`:""}{row.invoicedPrice!=null?` · FV ${money(row.invoicedPrice)}`:""}</span></div></div>)}{data.prices.length===0?<p className="empty-copy">Historia cen zbuduje się z jednego zakupu grupującego PO, PZ i fakturę.</p>:null}</div></details>
  <details className="module-panel"><summary><strong>Powiązania BOQ do decyzji · {String(links.proposed??0)}</strong></summary><div className="live-record-list">{data.links.filter(row=>row.status==="proposed").slice(0,25).map(row=><div key={String(row.id)} className="command-row"><div><small>{String(row.source_type)} → {String(row.target_type)}</small><strong>{Math.round(Number(row.confidence??0)*100)}% zgodności</strong><span>{String(row.relation_type)}</span></div>{canManage?<span><button onClick={()=>call("approve_link",{linkId:row.id}).catch(e=>setMessage(e.message))}><Check size={14}/> Zatwierdź</button><button onClick={()=>call("reject_link",{linkId:row.id}).catch(e=>setMessage(e.message))}><X size={14}/> Odrzuć</button></span>:null}</div>)}{!data.links.some(row=>row.status==="proposed")?<p className="empty-copy">Brak niezatwierdzonych dopasowań.</p>:null}</div></details>
 </section>;
}